import logging
from typing import Any, Type, Optional
from pydantic import BaseModel, ValidationError
from fastapi import HTTPException
from app.ai.providers.base import AIProvider

logger = logging.getLogger(__name__)

class ModelOutputValidationException(HTTPException):
    """Raised when the AI model fails to produce a valid schema after retries."""
    def __init__(self, detail: str):
        super().__init__(status_code=500, detail={
            "status": "error",
            "code": "AI_VALIDATION_FAILED",
            "message": "The AI model failed to produce a valid response structure.",
            "developer_details": detail
        })

class StructuredValidator:
    """
    Ensures that every response generated by the AIProvider strictly adheres to the provided Pydantic ResponseSchema.
    Implements a single-retry logic loop with self-correction instructions if the model hallucinates a malformed structure.
    """
    
    def __init__(self, provider: AIProvider):
        self.provider = provider

    async def safe_generate_structured(
        self, 
        prompt: str, 
        response_schema: Type[BaseModel], 
        system_instruction: Optional[str] = None
    ) -> Any:
        
        try:
            # First attempt
            logger.info(f"Attempting structured generation for schema: {response_schema.__name__}")
            return await self.provider.generate_structured(
                prompt=prompt, 
                schema=response_schema, 
                system_instruction=system_instruction
            )
            
        except ValidationError as e:
            logger.warning(f"Initial validation failed. Attempting self-correction retry. Errors: {e.errors()}")
            
            # Extract precise error messages from Pydantic
            error_details = ", ".join([f"Field '{'.'.join(str(loc) for loc in err['loc'])}': {err['msg']}" for err in e.errors()])
            
            # Construct strict correction prompt
            correction_instruction = (
                f"SYSTEM_CORRECTION: Your previous output failed validation. "
                f"You MUST fix the following structural errors: {error_details}"
            )
            
            # Append correction to existing system instruction (if any)
            retry_instruction = f"{system_instruction}\n\n{correction_instruction}" if system_instruction else correction_instruction
            
            try:
                # Second attempt (Retry exactly once)
                logger.info("Executing self-correction retry...")
                return await self.provider.generate_structured(
                    prompt=prompt,
                    schema=response_schema,
                    system_instruction=retry_instruction
                )
            except ValidationError as retry_e:
                # Terminal failure
                logger.error("Self-correction retry failed. Aborting generation.")
                raise ModelOutputValidationException(f"Failed after retry. Errors: {retry_e.errors()}") from retry_e
            except Exception as ex:
                logger.error(f"Unexpected error during self-correction retry: {str(ex)}")
                raise ModelOutputValidationException(f"Unexpected error during retry: {str(ex)}") from ex
