import { FlightOffer, HotelOffer, TravelPackage, TravelExperience, TransferOffer, CarRentalOffer, VRScene, TripPlan, Booking, TravelDocument, CustomerLead, NotificationItem } from "../types";

export const APP_CONFIG = {
  name: "TRAVELVERSE AI",
  tagline: "Autonomous AI-Powered Travel Universe",
  version: "3.4.0",
  currencies: ["USD", "EUR", "GBP", "JPY", "CAD", "AUD"],
  languages: ["English", "Spanish", "French", "Japanese", "German", "Mandarin"],
};

export const SEED_FLIGHTS: FlightOffer[] = [
  {
    id: "fl-101",
    airline: "Quantum Airways",
    airlineCode: "QA",
    airlineLogo: "✈️",
    price: 645,
    currency: "USD",
    stops: 0,
    departureTime: "2026-09-12T08:30:00Z",
    arrivalTime: "2026-09-12T14:45:00Z",
    totalDuration: "6h 15m",
    originCity: "San Francisco",
    originCode: "SFO",
    destinationCity: "Tokyo",
    destinationCode: "HND",
    cabinClass: "Business",
    baggageIncluded: true,
    carbonEmissionKg: 380,
    ecoScore: "A",
    refundable: true,
    seatsRemaining: 4,
    segments: [
      {
        id: "seg-1",
        flightNumber: "QA 782",
        airline: "Quantum Airways",
        airlineCode: "QA",
        airlineLogo: "✈️",
        aircraft: "Boeing 787-9 Dreamliner",
        origin: { code: "SFO", name: "San Francisco Intl", city: "San Francisco", terminal: "I", time: "08:30" },
        destination: { code: "HND", name: "Tokyo Haneda", city: "Tokyo", terminal: "3", time: "14:45" },
        duration: "6h 15m",
        durationMinutes: 375,
        cabinClass: "Business",
        seat: "3A",
      },
    ],
  },
  {
    id: "fl-102",
    airline: "AeroLuxe International",
    airlineCode: "AL",
    airlineLogo: "🌐",
    price: 389,
    currency: "USD",
    stops: 1,
    departureTime: "2026-09-15T11:00:00Z",
    arrivalTime: "2026-09-15T22:30:00Z",
    totalDuration: "11h 30m",
    originCity: "New York",
    originCode: "JFK",
    destinationCity: "Paris",
    destinationCode: "CDG",
    cabinClass: "Economy",
    baggageIncluded: true,
    carbonEmissionKg: 490,
    ecoScore: "B",
    refundable: false,
    seatsRemaining: 9,
    segments: [
      {
        id: "seg-2a",
        flightNumber: "AL 104",
        airline: "AeroLuxe",
        airlineCode: "AL",
        airlineLogo: "🌐",
        aircraft: "Airbus A350-900",
        origin: { code: "JFK", name: "John F Kennedy", city: "New York", terminal: "4", time: "11:00" },
        destination: { code: "LHR", name: "London Heathrow", city: "London", terminal: "2", time: "19:00" },
        duration: "6h 00m",
        durationMinutes: 360,
        cabinClass: "Economy",
      },
      {
        id: "seg-2b",
        flightNumber: "AL 982",
        airline: "AeroLuxe",
        airlineCode: "AL",
        airlineLogo: "🌐",
        aircraft: "Airbus A320neo",
        origin: { code: "LHR", name: "London Heathrow", city: "London", terminal: "2", time: "20:45" },
        destination: { code: "CDG", name: "Paris Charles de Gaulle", city: "Paris", terminal: "2E", time: "22:30" },
        duration: "1h 45m",
        durationMinutes: 105,
        cabinClass: "Economy",
      },
    ],
  },
  {
    id: "fl-103",
    airline: "Empyrean Jetways",
    airlineCode: "EJ",
    airlineLogo: "✨",
    price: 1190,
    currency: "USD",
    stops: 0,
    departureTime: "2026-10-01T21:15:00Z",
    arrivalTime: "2026-10-02T13:40:00Z",
    totalDuration: "14h 25m",
    originCity: "Los Angeles",
    originCode: "LAX",
    destinationCity: "Sydney",
    destinationCode: "SYD",
    cabinClass: "First",
    baggageIncluded: true,
    carbonEmissionKg: 620,
    ecoScore: "A",
    refundable: true,
    seatsRemaining: 2,
    segments: [
      {
        id: "seg-3",
        flightNumber: "EJ 001",
        airline: "Empyrean Jetways",
        airlineCode: "EJ",
        airlineLogo: "✨",
        aircraft: "Airbus A380-800 SkySuite",
        origin: { code: "LAX", name: "Los Angeles Intl", city: "Los Angeles", terminal: "B", time: "21:15" },
        destination: { code: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", terminal: "1", time: "13:40" },
        duration: "14h 25m",
        durationMinutes: 865,
        cabinClass: "First",
        seat: "1K",
      },
    ],
  },
  {
    id: "fl-104",
    airline: "Nordic Aurora Air",
    airlineCode: "NA",
    airlineLogo: "❄️",
    price: 290,
    currency: "USD",
    stops: 0,
    departureTime: "2026-11-05T09:10:00Z",
    arrivalTime: "2026-11-05T13:20:00Z",
    totalDuration: "4h 10m",
    originCity: "London",
    originCode: "LHR",
    destinationCity: "Reykjavik",
    destinationCode: "KEF",
    cabinClass: "Premium Economy",
    baggageIncluded: true,
    carbonEmissionKg: 210,
    ecoScore: "A",
    refundable: true,
    seatsRemaining: 12,
    segments: [
      {
        id: "seg-4",
        flightNumber: "NA 441",
        airline: "Nordic Aurora",
        airlineCode: "NA",
        airlineLogo: "❄️",
        aircraft: "Boeing 737 MAX 8",
        origin: { code: "LHR", name: "Heathrow", city: "London", terminal: "5", time: "09:10" },
        destination: { code: "KEF", name: "Keflavik", city: "Reykjavik", terminal: "1", time: "13:20" },
        duration: "4h 10m",
        durationMinutes: 250,
        cabinClass: "Premium Economy",
      },
    ],
  },
  {
    id: "fl-105",
    airline: "Emirates Royal Sky",
    airlineCode: "EK",
    airlineLogo: "🌟",
    price: 840,
    currency: "USD",
    stops: 0,
    departureTime: "2026-09-20T14:30:00Z",
    arrivalTime: "2026-09-21T07:15:00Z",
    totalDuration: "12h 45m",
    originCity: "New York",
    originCode: "JFK",
    destinationCity: "Dubai",
    destinationCode: "DXB",
    cabinClass: "Business",
    baggageIncluded: true,
    carbonEmissionKg: 520,
    ecoScore: "A",
    refundable: true,
    seatsRemaining: 6,
    segments: [
      {
        id: "seg-5",
        flightNumber: "EK 202",
        airline: "Emirates Royal Sky",
        airlineCode: "EK",
        airlineLogo: "🌟",
        aircraft: "Airbus A380 SkyLounge",
        origin: { code: "JFK", name: "John F Kennedy", city: "New York", terminal: "4", time: "14:30" },
        destination: { code: "DXB", name: "Dubai International", city: "Dubai", terminal: "3", time: "07:15" },
        duration: "12h 45m",
        durationMinutes: 765,
        cabinClass: "Business",
        seat: "7A",
      },
    ],
  },
  {
    id: "fl-106",
    airline: "Swiss Alpine Wings",
    airlineCode: "LX",
    airlineLogo: "🇨🇭",
    price: 520,
    currency: "USD",
    stops: 0,
    departureTime: "2026-10-10T10:00:00Z",
    arrivalTime: "2026-10-10T12:00:00Z",
    totalDuration: "2h 00m",
    originCity: "London",
    originCode: "LHR",
    destinationCity: "Zurich",
    destinationCode: "ZRH",
    cabinClass: "Business",
    baggageIncluded: true,
    carbonEmissionKg: 140,
    ecoScore: "A",
    refundable: true,
    seatsRemaining: 8,
    segments: [
      {
        id: "seg-6",
        flightNumber: "LX 317",
        airline: "Swiss Alpine Wings",
        airlineCode: "LX",
        airlineLogo: "🇨🇭",
        aircraft: "Airbus A220-300",
        origin: { code: "LHR", name: "Heathrow", city: "London", terminal: "2", time: "10:00" },
        destination: { code: "ZRH", name: "Zurich Airport", city: "Zurich", terminal: "1", time: "12:00" },
        duration: "2h 00m",
        durationMinutes: 120,
        cabinClass: "Business",
      },
    ],
  },
];

export const SEED_HOTELS: HotelOffer[] = [
  {
    id: "ht-201",
    name: "Aman Tokyo Sky Sanctuary",
    city: "Tokyo",
    country: "Japan",
    address: "The Otemachi Tower, 1-5-6 Otemachi, Chiyoda-ku",
    rating: 4.95,
    reviewsCount: 1420,
    pricePerNight: 890,
    currency: "USD",
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=2400&q=80",
    amenities: ["360° Skyline View", "Traditional Onsen Spa", "Michelin Omakase", "High-speed Starlink", "Infinity Lap Pool", "Butler Service"],
    tags: ["Luxury", "Skyline", "Spa", "Top Rated"],
    description: "Suspended high above the Imperial Palace gardens, Aman Tokyo harmonizes serene Japanese washi architecture with breathtaking metropolis panoramas.",
    coordinates: { lat: 35.6882, lng: 139.7635 },
    rooms: [
      {
        id: "rm-1",
        name: "Deluxe Imperial Suite",
        bedType: "1 King Bed + Tatami Lounge",
        capacity: 3,
        pricePerNight: 890,
        sqm: 98,
        amenities: ["Hinoki Wood Soaking Tub", "Complimentary Minibar", "Nespresso Atelier"],
        imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
      {
        id: "rm-2",
        name: "Panorama Sky Pavilion",
        bedType: "2 Queen Beds",
        capacity: 4,
        pricePerNight: 1250,
        sqm: 140,
        amenities: ["Private Onsen", "Personal Sommelier", "Private Dining Terrace"],
        imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
  },
  {
    id: "ht-202",
    name: "Soneva Jani Overwater Lagoon",
    city: "Noonu Atoll",
    country: "Maldives",
    address: "Medhufaru Island, Noonu Atoll",
    rating: 4.98,
    reviewsCount: 890,
    pricePerNight: 1480,
    currency: "USD",
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=2400&q=80",
    amenities: ["Retractable Stargazing Roof", "Water Slide into Lagoon", "Private Catamaran", "Barefoot Butler", "Eco-Solar Powered"],
    tags: ["Ultra-Luxury", "Eco", "Overwater Villa", "Honeymoon"],
    description: "Villas perched over crystalline waters with private slides straight into the azure Indian Ocean and master bedrooms with roofs that open to constellations.",
    coordinates: { lat: 5.8672, lng: 73.3421 },
    rooms: [
      {
        id: "rm-3",
        name: "1-Bedroom Water Retreat with Slide",
        bedType: "King Bed",
        capacity: 2,
        pricePerNight: 1480,
        sqm: 411,
        amenities: ["Lagoon Slide", "Private Plunge Pool", "Catamaran Netting Lounge"],
        imageUrl: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
  },
  {
    id: "ht-203",
    name: "Canaves Oia Epitome Luxury Suites",
    city: "Santorini",
    country: "Greece",
    address: "Oia, Santorini 847 02",
    rating: 4.92,
    reviewsCount: 1105,
    pricePerNight: 720,
    currency: "USD",
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=2400&q=80",
    amenities: ["Caldera Sunset View", "Infinity Pool", "Private Wine Cellar", "Helipad Access", "Greek Gourmet Bistro"],
    tags: ["Romantic", "Caldera", "Infinity Pool", "Sunsets"],
    description: "Perched majestically above the fishing village of Ammoudi, offering front-row sunset views over the Aegean Sea with private infinity plunge pools.",
    coordinates: { lat: 36.4618, lng: 25.3753 },
    rooms: [
      {
        id: "rm-4",
        name: "Honeymoon Sunset Suite",
        bedType: "Super King",
        capacity: 2,
        pricePerNight: 720,
        sqm: 75,
        amenities: ["Private Heated Infinity Pool", "Sunset Veranda"],
        imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
  },
  {
    id: "ht-204",
    name: "The Chedi Andermatt Alpine Lodge",
    city: "Andermatt",
    country: "Switzerland",
    address: "Gotthardstrasse 4, 6490 Andermatt",
    rating: 4.96,
    reviewsCount: 960,
    pricePerNight: 850,
    currency: "USD",
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517840905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=2400&q=80",
    amenities: ["Ski-in/Ski-out Butler", "2400m² Hydrotherapy Spa", "The Cheese Tower", "Fireplace in every room"],
    tags: ["Alpine", "Ski", "Spa", "Winter"],
    description: "An extraordinary fusion of Alpine chic and Asian serenity in the heart of the Swiss Alps, boasting indoor fireplaces, warm timber, and hydrotherapy thermal pools.",
    coordinates: { lat: 46.6344, lng: 8.5947 },
    rooms: [
      {
        id: "rm-5",
        name: "Gemsstock Alpine Suite",
        bedType: "Hästens King Bed",
        capacity: 2,
        pricePerNight: 850,
        sqm: 110,
        amenities: ["Granite Fireplace", "Mountain Balcony", "Heated Stone Floors"],
        imageUrl: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
  },
  {
    id: "ht-205",
    name: "Atlantis The Royal & Burj Al Arab Luxury Stays",
    city: "Dubai",
    country: "UAE",
    address: "Crescent Rd, Palm Jumeirah, Dubai",
    rating: 4.98,
    reviewsCount: 2310,
    pricePerNight: 1250,
    currency: "USD",
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=2400&q=80",
    amenities: ["Rooftop Cloud 22 Infinity Pool", "Private Beach", "Michelin Dining by Heston", "Rolls-Royce Chauffeur", "24h Personal Butler", "Helipad"],
    tags: ["Ultra-Luxury", "Palm Jumeirah", "Infinity Pool", "VIP"],
    description: "The world's most experiential ultra-luxury resort with sky-high infinity pools, fire & water fountain spectacles, and Michelin-starred gastronomy.",
    coordinates: { lat: 25.1378, lng: 55.1278 },
    rooms: [
      {
        id: "rm-6",
        name: "Sky Pool Villa Suite",
        bedType: "Emperor Bed",
        capacity: 3,
        pricePerNight: 1250,
        sqm: 160,
        amenities: ["Private Glass Infinity Pool", "Hermès Amenities", "Butler Service"],
        imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
  },
  {
    id: "ht-206",
    name: "Armani Hotel Dubai",
    city: "Dubai",
    country: "UAE",
    address: "Burj Khalifa, 1 Sheikh Mohammed bin Rashid Blvd, Downtown Dubai",
    rating: 4.92,
    reviewsCount: 1640,
    pricePerNight: 680,
    currency: "USD",
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1546412414-e1885259563a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=2400&q=80",
    amenities: ["Burj Khalifa Direct Access", "Armani/SPA", "Dubai Fountain Views", "Private Lifestyle Manager"],
    tags: ["Downtown", "Architecture", "Luxury", "Spa"],
    description: "Nestled within the world's tallest tower, designed by Giorgio Armani himself, offering bespoke hospitality and breathtaking fountain panoramas.",
    coordinates: { lat: 25.1972, lng: 55.2744 },
    rooms: [
      {
        id: "rm-7",
        name: "Armani Fountain Suite",
        bedType: "King Bed",
        capacity: 2,
        pricePerNight: 680,
        sqm: 85,
        amenities: ["Direct Fountain Vista", "iPad Room Automation", "Armani Silk Robes"],
        imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
  },
  {
    id: "ht-207",
    name: "Hôtel de Crillon, A Rosewood Hotel",
    city: "Paris",
    country: "France",
    address: "10 Place de la Concorde, 75008 Paris",
    rating: 4.96,
    reviewsCount: 1210,
    pricePerNight: 1150,
    currency: "USD",
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=2400&q=80",
    amenities: ["Sense Spa", "Courtyard Garden", "Karl Lagerfeld Grands Appartements", "Eiffel Tower View"],
    tags: ["Historic Palace", "Eiffel View", "Fine Dining", "Luxury"],
    description: "An iconic 18th-century palace on Place de la Concorde celebrating Parisian art de vivre, haute gastronomy, and bespoke luxury.",
    coordinates: { lat: 48.8672, lng: 2.3218 },
    rooms: [
      {
        id: "rm-8",
        name: "Grand Premier Suite Concorde",
        bedType: "King Bed",
        capacity: 2,
        pricePerNight: 1150,
        sqm: 90,
        amenities: ["Marble Fireplace", "Palace Courtyard View", "Bespoke Butler"],
        imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
  },
];

export const SEED_PACKAGES: TravelPackage[] = [
  {
    id: "pkg-301",
    title: "Tokyo Cyber-Pulse & Kyoto Zen Epoch",
    tagline: "High-speed Shinkansen, Michelin ramen tours, bamboo groves & private tea master ceremony.",
    destination: "Tokyo & Kyoto",
    country: "Japan",
    days: 8,
    nights: 7,
    price: 3490,
    originalPrice: 4200,
    currency: "USD",
    travelStyle: "cultural",
    rating: 4.97,
    reviewsCount: 340,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    ],
    highlights: [
      "Shinkansen Gran Class Bullet Train passes included",
      "Exclusive private tea ceremony in 400-year-old Kyoto temple",
      "Guided robot & digital art lab tour in Odaiba",
      "5-star ryokan stay with private thermal onsen bath",
      "AI pocket concierge & pocket WiFi included",
    ],
    included: [
      "7 Nights 5-Star Luxury Accommodations",
      "All Shinkansen Gran Class transfers",
      "Daily gourmet breakfasts & 3 curated chef dinners",
      "English-speaking master cultural guide",
      "Full VIP airport luggage transfers",
    ],
    notIncluded: ["International flights (available as add-on)", "Personal souvenir shopping", "Travel insurance"],
    departureDates: ["2026-09-15", "2026-10-01", "2026-10-20", "2026-11-10"],
    itinerarySummary: [
      { day: 1, title: "Arrival in Tokyo & Shinjuku Sky Welcome", desc: "Private chauffeur greeting, hotel check-in at Aman Tokyo, and welcome dinner." },
      { day: 2, title: "Odaiba Immersive Arts & Tsukiji Market", desc: "VIP early entry to teamLab Planets followed by private seafood tasting." },
      { day: 3, title: "Bullet Train to Kyoto & Gion Lanterns", desc: "Shinkansen across Mt. Fuji vista to Kyoto. Evening twilight walk through geisha district." },
      { day: 4, title: "Arashiyama Bamboo Forest & Zen Meditation", desc: "Early dawn walk through bamboo grove with private temple Abbot guidance." },
      { day: 5, title: "Fushimi Inari Torii Shrine & Uji Matcha Tasting", desc: "Private photography masterclass through thousands of vermilion gates." },
      { day: 6, title: "Nara Deer Park & Ancient Cedar Pagodas", desc: "Excursion to Todai-ji Great Buddha and ancient Nara deer park." },
      { day: 7, title: "Return to Tokyo & Shibuya Crossing Nightlights", desc: "Rooftop cocktail tasting overlooking world's busiest crossing." },
      { day: 8, title: "Sayonara Tokyo", desc: "Curated shopping guidance in Ginza followed by luxury limousine transfer to Haneda." },
    ],
  },
  {
    id: "pkg-302",
    title: "Amalfi Coast Private Yacht & Cliffside Villas",
    tagline: "Positano, Capri Blue Grotto by Riva boat, Ravello infinity gardens & lemon grove dining.",
    destination: "Amalfi Coast & Capri",
    country: "Italy",
    days: 6,
    nights: 5,
    price: 4150,
    originalPrice: 4890,
    currency: "USD",
    travelStyle: "luxury",
    rating: 4.99,
    reviewsCount: 215,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80",
    ],
    highlights: [
      "Private 48ft Riva Yacht charter around Capri & Faraglioni Rocks",
      "Cliffside villa suite with heated plunge pool in Positano",
      "Private Michelin chef cooking workshop in historic Ravello",
      "Helicopter tour over Vesuvius & Gulf of Naples",
    ],
    included: ["5 Nights 5-Star Cliffside Suite", "Private Skipper Yacht Day", "Daily breakfast & wine pairings", "Helicopter transfers"],
    notIncluded: ["International flights", "Gratuities"],
    departureDates: ["2026-09-10", "2026-09-24", "2026-10-08"],
    itinerarySummary: [
      { day: 1, title: "Naples to Positano Helicopter Arrival", desc: "Scenic aerial transfer landing at cliffside helipad, aperitivo at sunset." },
      { day: 2, title: "Capri Island & Blue Grotto by Riva Yacht", desc: "Full day cruising secret sea caves and swimming in cobalt bays." },
      { day: 3, title: "Ravello Villa Cimbrone & Infinity Terrace", desc: "Stroll along the terrace of infinity followed by private lemon grove lunch." },
      { day: 4, title: "Path of the Gods Hiking & Sunset Wine", desc: "Guided coastal hike high above the clouds with panoramic vistas." },
      { day: 5, title: "Positano Beach Club & Gourmet Seafood Farewell", desc: "Reserved front row loungers at La Fontelina." },
      { day: 6, title: "Arrivederci Italia", desc: "Private boat transfer to Naples." },
    ],
  },
  {
    id: "pkg-303",
    title: "Swiss Alpine Glacier Express & Zermatt Matterhorn",
    tagline: "Panoramic glass-domed trains, luxury thermal spas, and Matterhorn mountain safaris.",
    destination: "St. Moritz & Zermatt",
    country: "Switzerland",
    days: 7,
    nights: 6,
    price: 3680,
    currency: "USD",
    travelStyle: "adventure",
    rating: 4.93,
    reviewsCount: 180,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80",
    ],
    highlights: ["Glacier Express Excellence Class Train", "Gornergrat railway ride to Matterhorn viewpoints", "Fondue dinner on horse-drawn sleigh"],
    included: ["6 Nights luxury alpine resorts", "Excellence Class Swiss Pass", "Spa access & all meals"],
    notIncluded: ["Ski equipment rental"],
    departureDates: ["2026-11-01", "2026-11-20", "2026-12-05"],
    itinerarySummary: [
      { day: 1, title: "Zurich to St. Moritz", desc: "Scenic transfer into the Engadin valley." },
      { day: 2, title: "St. Moritz Alpine Glaciers", desc: "Spa day at mineral springs." },
      { day: 3, title: "The Glacier Express Journey", desc: "8-hour panoramic rail trip across 291 bridges and 91 tunnels." },
      { day: 4, title: "Arrival in Zermatt", desc: "Car-free village exploration and Matterhorn view." },
      { day: 5, title: "Gornergrat 3,089m Ridge", desc: "Glacier viewpoints and alpine hike." },
      { day: 6, title: "Thermal Spa & Swiss Fondue Night", desc: "Relaxation with alpine herbal baths." },
      { day: 7, title: "Geneva Departure", desc: "First-class rail to Geneva Airport." },
    ],
  },
];

export const SEED_EXPERIENCES: TravelExperience[] = [
  {
    id: "exp-401",
    title: "Tokyo Cyber-Night Foodie Odyssey: 7 Hidden Izakayas & Alley Bars",
    category: "Culinary",
    city: "Tokyo",
    country: "Japan",
    duration: "4.5 hours",
    price: 135,
    currency: "USD",
    rating: 4.98,
    reviewsCount: 1680,
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
    guideLanguage: ["English", "Japanese"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    description: "Venture deep into Shinjuku Omoide Yokocho and Golden Gai with a local culinary insider. Taste charcoal-grilled wagyu skewers, handmade gyoza, seasonal sake pairings, and artisan whiskey cocktails in 6-seat subterranean bars.",
    meetingPoint: "East Exit of Shinjuku JR Station under Studio Alta screen",
  },
  {
    id: "exp-402",
    title: "Santorini Sunset Catamaran Sailing with Unlimited Greek BBQ & Wine",
    category: "Water Sport",
    city: "Santorini",
    country: "Greece",
    duration: "5 hours",
    price: 175,
    currency: "USD",
    rating: 4.96,
    reviewsCount: 2240,
    imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80",
    guideLanguage: ["English", "Greek", "French"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 48 hours before start",
    description: "Sail past the Red Beach, White Beach, and soak in the volcanic hot springs inside the Caldera. Enjoy freshly grilled souvlaki skewers, Greek salad, fresh fish, and local Assyrtiko white wine as the world's most famous sunset illuminates the cliffs.",
    meetingPoint: "Vlychada Marina Pier 4 (Hotel pickup included)",
  },
  {
    id: "exp-403",
    title: "Reykjavik Aurora Borealis Hunt by 4x4 Superjeep with Astrophotographer",
    category: "Adventure",
    city: "Reykjavik",
    country: "Iceland",
    duration: "4 hours",
    price: 195,
    currency: "USD",
    rating: 4.94,
    reviewsCount: 980,
    imageUrl: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=800&q=80",
    guideLanguage: ["English"],
    instantConfirmation: true,
    cancellationPolicy: "Free re-booking if Aurora is not visible",
    description: "Trek into remote lava fields away from all city light pollution in a monster 4x4 Superjeep. Enjoy hot cocoa with Icelandic schnapps while our professional astrophotographer captures high-res portraits of you beneath the dancing Northern Lights.",
    meetingPoint: "Hotel pickup across Reykjavik metropolitan area",
  },
  {
    id: "exp-404",
    title: "Dubai Desert Platinum Heritage Falconry & Bedouin Royal Dinner",
    category: "Cultural",
    city: "Dubai",
    country: "UAE",
    duration: "7 hours",
    price: 240,
    currency: "USD",
    rating: 4.97,
    reviewsCount: 1450,
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80",
    guideLanguage: ["English", "Arabic", "German"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    description: "Ride vintage 1950s open-top Land Rovers through the Dubai Desert Conservation Reserve. Witness royal falconry demonstrations and dine under the stars at a private oasis torchlit camp with 6-course Emirati gastronomy.",
    meetingPoint: "Downtown Dubai & Palm Jumeirah hotel pickups",
  },
];

export const SEED_TRANSFERS: TransferOffer[] = [
  {
    id: "tr-101",
    title: "Dubai Intl (DXB) to Palm Jumeirah VIP Chauffeur",
    vehicleType: "Luxury Sedan",
    originCity: "Dubai",
    originLocation: "Dubai International Airport (DXB)",
    destinationCity: "Dubai",
    destinationLocation: "Palm Jumeirah & Downtown",
    price: 140,
    currency: "USD",
    duration: "35 mins",
    durationMinutes: 35,
    passengers: 3,
    luggage: 3,
    rating: 4.98,
    reviewsCount: 840,
    amenities: ["Flight Delay Tracking", "Bottled Artesian Water", "High-Speed Wi-Fi", "Meet & Greet with Name Sign", "Cold Towels"],
    imageUrl: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    driverLanguage: ["English", "Arabic", "Russian"],
    freeCancellation: true,
    instantConfirmation: true,
    meetAndGreet: true,
    flightTracking: true,
    carbonOffsetKg: 12,
    travelPreferencesMatch: ["Luxury", "Business", "Family"],
  },
  {
    id: "tr-102",
    title: "Tokyo Haneda (HND) to Shinjuku Autonomous Executive Van",
    vehicleType: "First Class Van",
    originCity: "Tokyo",
    originLocation: "Tokyo Haneda Airport (HND)",
    destinationCity: "Tokyo",
    destinationLocation: "Shinjuku / Shibuya / Ginza",
    price: 110,
    currency: "USD",
    duration: "40 mins",
    durationMinutes: 40,
    passengers: 6,
    luggage: 6,
    rating: 4.96,
    reviewsCount: 620,
    amenities: ["Reclining Captain Chairs", "High-Speed 5G Wi-Fi", "USB-C Charging Hub", "English Speaking Host"],
    imageUrl: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=800&q=80",
    driverLanguage: ["English", "Japanese"],
    freeCancellation: true,
    instantConfirmation: true,
    meetAndGreet: true,
    flightTracking: true,
    carbonOffsetKg: 15,
    travelPreferencesMatch: ["Family", "Business", "Culture"],
  },
  {
    id: "tr-103",
    title: "Malé Airport to Soneva Jani VIP Twin-Otter Seaplane",
    vehicleType: "Helicopter",
    originCity: "Malé",
    originLocation: "Velana International Airport (MLE)",
    destinationCity: "Noonu Atoll",
    destinationLocation: "Soneva Jani Water Retreats",
    price: 480,
    currency: "USD",
    duration: "45 mins",
    durationMinutes: 45,
    passengers: 10,
    luggage: 10,
    rating: 4.99,
    reviewsCount: 310,
    amenities: ["Panoramic Atoll Aerial View", "VIP Seaplane Lounge Access", "Chilled Champagne", "Noise-Cancelling Headsets"],
    imageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    driverLanguage: ["English"],
    freeCancellation: true,
    instantConfirmation: true,
    meetAndGreet: true,
    flightTracking: true,
    carbonOffsetKg: 45,
    travelPreferencesMatch: ["Luxury", "Romantic", "Wellness"],
  },
  {
    id: "tr-104",
    title: "Paris Charles de Gaulle (CDG) to Central Paris Premium Chauffeur",
    vehicleType: "Electric Chauffeur",
    originCity: "Paris",
    originLocation: "Charles de Gaulle Airport (CDG)",
    destinationCity: "Paris",
    destinationLocation: "1st - 8th Arrondissement (Eiffel / Louvre)",
    price: 95,
    currency: "USD",
    duration: "45 mins",
    durationMinutes: 45,
    passengers: 3,
    luggage: 3,
    rating: 4.94,
    reviewsCount: 1120,
    amenities: ["Zero-Emission Mercedes EQE", "Bottled Evian", "Custom Spotify Playlist", "Flight Delay Tracking"],
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    driverLanguage: ["English", "French"],
    freeCancellation: true,
    instantConfirmation: true,
    meetAndGreet: true,
    flightTracking: true,
    carbonOffsetKg: 0,
    travelPreferencesMatch: ["Eco", "Business", "Romantic"],
  },
  {
    id: "tr-105",
    title: "Dubai Marina to Abu Dhabi Louvre Private Helicopter Express",
    vehicleType: "Helicopter",
    originCity: "Dubai",
    originLocation: "Dubai Marina Helipad",
    destinationCity: "Abu Dhabi",
    destinationLocation: "Louvre Abu Dhabi & Saadiyat Island",
    price: 650,
    currency: "USD",
    duration: "25 mins",
    durationMinutes: 25,
    passengers: 4,
    luggage: 4,
    rating: 4.99,
    reviewsCount: 190,
    amenities: ["Aerial Palm & Sheikh Zayed Mosque View", "VIP Terminal Fast-Track", "Complimentary Lounge Access"],
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80",
    driverLanguage: ["English", "Arabic"],
    freeCancellation: false,
    instantConfirmation: true,
    meetAndGreet: true,
    flightTracking: false,
    travelPreferencesMatch: ["Luxury", "Adventure"],
  },
  {
    id: "tr-106",
    title: "Naples Port to Positano Luxury Riva Speedboat Taxi",
    vehicleType: "Private Speedboat",
    originCity: "Naples",
    originLocation: "Molo Beverello Port, Naples",
    destinationCity: "Positano",
    destinationLocation: "Positano Main Beach Dock",
    price: 290,
    currency: "USD",
    duration: "40 mins",
    durationMinutes: 40,
    passengers: 6,
    luggage: 6,
    rating: 4.97,
    reviewsCount: 420,
    amenities: ["Sorrento Coastline Panoramic Cruise", "Chilled Prosecco", "Sunbathing Deck", "Luggage Porter Service"],
    imageUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
    driverLanguage: ["English", "Italian"],
    freeCancellation: true,
    instantConfirmation: true,
    meetAndGreet: true,
    flightTracking: false,
    travelPreferencesMatch: ["Romantic", "Luxury", "Adventure"],
  },
];

export const SEED_CARS: CarRentalOffer[] = [
  {
    id: "car-201",
    model: "Taycan 4S Cross Turismo",
    brand: "Porsche",
    category: "Electric",
    city: "Dubai",
    country: "UAE",
    pickupLocation: "Dubai International Airport (DXB) Terminal 3 VIP",
    pricePerDay: 280,
    currency: "USD",
    seats: 4,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    mileage: "Unlimited",
    rating: 4.98,
    reviewsCount: 410,
    imageUrl: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    amenities: ["Free Supercharging in UAE", "Apple CarPlay & HUD", "Adaptive Cruise Control", "Glass Panoramic Roof"],
    freeCancellation: true,
    instantConfirmation: true,
    supplier: "AeroLuxe Prestige Cars",
    insuranceIncluded: true,
    travelPreferencesMatch: ["Luxury", "Eco", "Business"],
  },
  {
    id: "car-202",
    model: "Range Rover Autobiography P530",
    brand: "Land Rover",
    category: "SUV",
    city: "Dubai",
    country: "UAE",
    pickupLocation: "Downtown Dubai & Palm Jumeirah Delivery",
    pricePerDay: 340,
    currency: "USD",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Hybrid",
    mileage: "Unlimited",
    rating: 4.96,
    reviewsCount: 380,
    imageUrl: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
    amenities: ["Executive Rear Class Seating", "Meridian 3D Sound", "All-Terrain Sand Driving Mode", "Ventilated Massage Seats"],
    freeCancellation: true,
    instantConfirmation: true,
    supplier: "Emirates Sovereign Fleet",
    insuranceIncluded: true,
    travelPreferencesMatch: ["Family", "Luxury", "Adventure"],
  },
  {
    id: "car-203",
    model: "Model X Plaid Tri-Motor (1020 HP)",
    brand: "Tesla",
    category: "Electric",
    city: "Tokyo",
    country: "Japan",
    pickupLocation: "Tokyo Haneda Airport (HND)",
    pricePerDay: 210,
    currency: "USD",
    seats: 6,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Electric",
    mileage: "Unlimited",
    rating: 4.95,
    reviewsCount: 295,
    imageUrl: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80",
    amenities: ["Falcon Wing Doors", "Full Self-Driving Autopilot", "ETC Highway Card Included", "Zero Emissions"],
    freeCancellation: true,
    instantConfirmation: true,
    supplier: "NeoTokyo Electric",
    insuranceIncluded: true,
    travelPreferencesMatch: ["Family", "Eco", "Adventure"],
  },
  {
    id: "car-204",
    model: "Ferrari F8 Tributo Spider",
    brand: "Ferrari",
    category: "Sports",
    city: "Paris",
    country: "France",
    pickupLocation: "Paris Charles de Gaulle or Champs-Élysées",
    pricePerDay: 950,
    currency: "USD",
    seats: 2,
    doors: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "250 km/day",
    rating: 4.99,
    reviewsCount: 140,
    imageUrl: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80",
    amenities: ["Retractable Hard Top", "JBL Premium Audio", "Track Telemetry", "Complimentary Valet Delivery"],
    freeCancellation: false,
    instantConfirmation: true,
    supplier: "Monaco & Paris Supercars",
    insuranceIncluded: true,
    travelPreferencesMatch: ["Luxury", "Romantic"],
  },
  {
    id: "car-205",
    model: "G63 AMG V8 Biturbo",
    brand: "Mercedes-Benz",
    category: "SUV",
    city: "Dubai",
    country: "UAE",
    pickupLocation: "Dubai International Airport (DXB)",
    pricePerDay: 490,
    currency: "USD",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "Unlimited",
    rating: 4.97,
    reviewsCount: 520,
    imageUrl: "https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&w=800&q=80",
    amenities: ["Burmester Surround Sound", "Carbon Fiber Trim", "Desert Drive Protection", "360° Surround Camera"],
    freeCancellation: true,
    instantConfirmation: true,
    supplier: "VIP Gulf Motors",
    insuranceIncluded: true,
    travelPreferencesMatch: ["Luxury", "Adventure"],
  },
  {
    id: "car-206",
    model: "BMW i7 xDrive60 Excellence",
    brand: "BMW",
    category: "Executive",
    city: "London",
    country: "UK",
    pickupLocation: "London Heathrow Terminal 5",
    pricePerDay: 260,
    currency: "USD",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    mileage: "Unlimited",
    rating: 4.94,
    reviewsCount: 220,
    imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    amenities: ["31.3\" 8K Theater Screen", "Bowers & Wilkins Diamond Sound", "Executive Lounge Seating", "Clean Air Zone Exempt"],
    freeCancellation: true,
    instantConfirmation: true,
    supplier: "Mayfair Executive Fleet",
    insuranceIncluded: true,
    travelPreferencesMatch: ["Business", "Luxury", "Eco"],
  },
  {
    id: "car-207",
    model: "RS6 Avant Quattro All-Weather",
    brand: "Audi",
    category: "Executive",
    city: "Zurich",
    country: "Switzerland",
    pickupLocation: "Zurich Airport (ZRH) Center",
    pricePerDay: 230,
    currency: "USD",
    seats: 5,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Hybrid",
    mileage: "Unlimited",
    rating: 4.95,
    reviewsCount: 310,
    imageUrl: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80",
    amenities: ["Swiss Highway Vignette Included", "Roof Ski Box", "Winter Studded Tyres", "Bang & Olufsen 3D Sound"],
    freeCancellation: true,
    instantConfirmation: true,
    supplier: "Swiss Alpine Rentals",
    insuranceIncluded: true,
    travelPreferencesMatch: ["Adventure", "Family", "Wellness"],
  },
];

export const SEED_VR_SCENES: VRScene[] = [
  {
    id: "vr-1",
    title: "Maldives Coral Lagoon Overwater Retreat",
    destination: "Noonu Atoll",
    country: "Maldives",
    type: "underwater",
    panoramaUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=2400&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=600&q=80",
    description: "Immerse in the crystal-clear turquoise waters of the Indian Ocean, gaze at manta rays gliding across coral heads, and explore the spacious overwater villa deck.",
    hotspots: [
      { id: "h1", title: "Coral Reef Sanctuary", description: "Home to 200+ marine species and vibrant soft corals.", x: 25, y: 60, tag: "Marine Life" },
      { id: "h2", title: "Overwater Stargazing Lounge", description: "Open mesh hammock suspended directly over the water.", x: 75, y: 40, tag: "Architecture" },
      { id: "h3", title: "Water Villa Lagoon Slide", description: "Curved slide launching straight into 28°C ocean waters.", x: 50, y: 35, tag: "Feature" },
    ],
  },
  {
    id: "vr-2",
    title: "Tokyo Shibuya Sky at Twilight",
    destination: "Tokyo",
    country: "Japan",
    type: "360-landscape",
    panoramaUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=2400&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=600&q=80",
    description: "Experience the hyper-futuristic neon pulse of Tokyo from 230 meters above the world-famous scramble crossing as Mount Fuji silhouettes against purple twilight.",
    hotspots: [
      { id: "h4", title: "Mount Fuji Vista", description: "Visible in clear skies 100km to the west.", x: 15, y: 30, tag: "Landmark" },
      { id: "h5", title: "Shibuya Crossing", description: "Crossed by up to 3,000 people per pedestrian green signal.", x: 60, y: 80, tag: "Urban Hotspot" },
    ],
  },
  {
    id: "vr-3",
    title: "Swiss Alps Glacier Express Panorama Car",
    destination: "Andermatt",
    country: "Switzerland",
    type: "360-landscape",
    panoramaUrl: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=2400&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=600&q=80",
    description: "Sit inside the curved glass observation dome as the Glacier Express carves through snow-capped valleys, frozen waterfalls, and stone viaducts.",
    hotspots: [
      { id: "h6", title: "Landwasser Viaduct", description: "65-meter-high curved limestone bridge built in 1901.", x: 45, y: 55, tag: "Engineering" },
      { id: "h7", title: "Oberalp Pass Summit", description: "Highest point of the line at 2,033 meters above sea level.", x: 80, y: 25, tag: "Nature" },
    ],
  },
];

export const SEED_TRIPS: TripPlan[] = [
  {
    id: "trip-01",
    title: "Autumn Serenade in Kyoto & Tokyo",
    destination: "Tokyo & Kyoto",
    country: "Japan",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    startDate: "2026-09-12",
    endDate: "2026-09-19",
    status: "upcoming",
    travelersCount: 2,
    budgetTotal: 4800,
    currency: "USD",
    isAIGenerated: true,
    emergencyContacts: [
      { name: "Tokyo Concierge Support", role: "Local Host", phone: "+81 3 5555 0199" },
      { name: "Global Travel SOS", role: "Insurance & Medical", phone: "+1 800 555 0123" },
    ],
    packingList: [
      { id: "p1", item: "Universal Travel Plug Adapter (Type A)", category: "Electronics", packed: true },
      { id: "p2", item: "Passport with 6+ months validity", category: "Documents", packed: true },
      { id: "p3", item: "Comfortable Walking Shoes for Temple Steps", category: "Apparel", packed: false },
      { id: "p4", item: "Light Autumn Jacket for Kyoto evenings", category: "Apparel", packed: false },
      { id: "p5", item: "Suica / Pasmo IC Card on Apple Wallet", category: "Transit", packed: true },
    ],
    days: [
      {
        dayNumber: 1,
        date: "2026-09-12",
        theme: "Arrival & Neon Glow in Shinjuku",
        weatherForecast: { tempC: 24, condition: "Clear & Crisp", icon: "☀️" },
        activities: [
          {
            id: "a1",
            time: "14:45",
            title: "Flight Arrival QA 782 at Tokyo Haneda (HND)",
            type: "flight",
            location: "Haneda Airport Terminal 3",
            description: "Clear automated biometric customs, meet private chauffeur at exit gate.",
            bookingRef: "TV-88921A",
            completed: false,
          },
          {
            id: "a2",
            time: "16:30",
            title: "Check-in at Aman Tokyo Sky Sanctuary",
            type: "hotel",
            location: "Otemachi Tower, Chiyoda-ku",
            description: "Unpack in Deluxe Imperial Suite, enjoy complimentary welcome matcha.",
            completed: false,
          },
          {
            id: "a3",
            time: "19:00",
            title: "Omakase Dinner at Sushi Shin",
            type: "meal",
            location: "Ginza 6-chome",
            description: "18-course seasonal Edomae sushi experience with master chef pairing.",
            cost: 220,
            completed: false,
          },
        ],
      },
      {
        dayNumber: 2,
        date: "2026-09-13",
        theme: "Ancient Heritage & Digital Art Realms",
        weatherForecast: { tempC: 23, condition: "Partly Sunny", icon: "🌤️" },
        activities: [
          {
            id: "a4",
            time: "09:00",
            title: "Asakusa Senso-ji Temple Dawn Stroll",
            type: "activity",
            location: "Asakusa, Taito City",
            description: "Visit Tokyo's oldest Buddhist temple before crowds arrive.",
            completed: false,
          },
          {
            id: "a5",
            time: "13:30",
            title: "teamLab Planets Tokyo VIP Interactive Experience",
            type: "activity",
            location: "Toyosu, Koto City",
            description: "Walk barefoot through water art exhibits and infinite crystal rooms.",
            cost: 45,
            completed: false,
          },
          {
            id: "a6",
            time: "18:30",
            title: "Shibuya Sky Observation Deck at Sunset",
            type: "activity",
            location: "Shibuya Scramble Square Rooftop",
            description: "Golden hour photo session overlooking the metropolis.",
            cost: 25,
            completed: false,
          },
        ],
      },
    ],
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: "bk-901",
    referenceNumber: "TV-88921A",
    userId: "usr-01",
    userName: "Alex Rivera",
    userEmail: "toppersclassess@gmail.com",
    type: "flight",
    title: "Quantum Airways QA 782 (SFO ➔ HND)",
    destination: "Tokyo, Japan",
    bookingDate: "2026-08-15",
    travelDate: "2026-09-12",
    status: "confirmed",
    totalAmount: 1290,
    currency: "USD",
    paymentMethod: "Visa ending in •••• 4242",
    paymentStatus: "paid",
    passengers: [
      { name: "Alex Rivera", type: "Adult", seat: "3A", ticketNumber: "016-9283718291" },
      { name: "Elena Rivera", type: "Adult", seat: "3B", ticketNumber: "016-9283718292" },
    ],
    details: {
      aircraft: "Boeing 787-9 Dreamliner",
      terminal: "Terminal 3",
      gate: "58B",
      boardingTime: "07:45 AM",
      cabinClass: "Business",
    },
    qrCodeUrl: "https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=TRAVELVERSE-TV-88921A-SFO-HND",
    pdfVoucherUrl: "#",
  },
  {
    id: "bk-902",
    referenceNumber: "TV-77219B",
    userId: "usr-01",
    userName: "Alex Rivera",
    userEmail: "toppersclassess@gmail.com",
    type: "hotel",
    title: "Aman Tokyo Sky Sanctuary (3 Nights)",
    destination: "Tokyo, Japan",
    bookingDate: "2026-08-16",
    travelDate: "2026-09-12",
    returnDate: "2026-09-15",
    status: "confirmed",
    totalAmount: 2670,
    currency: "USD",
    paymentMethod: "Apple Pay (Mastercard •••• 8812)",
    paymentStatus: "paid",
    passengers: [{ name: "Alex Rivera", type: "Adult" }, { name: "Elena Rivera", type: "Adult" }],
    details: {
      roomName: "Deluxe Imperial Suite",
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      breakfast: "Included (Japanese & Continental Omakase)",
    },
    qrCodeUrl: "https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=TRAVELVERSE-TV-77219B-AMAN-TOKYO",
    pdfVoucherUrl: "#",
  },
];

export const SEED_DOCUMENTS: TravelDocument[] = [
  {
    id: "doc-1",
    title: "E-Boarding Pass QA 782 (SFO ➔ HND)",
    type: "boarding_pass",
    bookingRef: "TV-88921A",
    holderName: "Alex Rivera",
    issueDate: "2026-08-15",
    expiryDate: "2026-09-12",
    status: "valid",
    fileSize: "1.2 MB",
    downloadUrl: "#",
    metadata: { Flight: "QA 782", Seat: "3A", Gate: "58B", Terminal: "I" },
  },
  {
    id: "doc-2",
    title: "Aman Tokyo Confirmed Hotel Voucher",
    type: "hotel_voucher",
    bookingRef: "TV-77219B",
    holderName: "Alex Rivera",
    issueDate: "2026-08-16",
    status: "valid",
    fileSize: "840 KB",
    downloadUrl: "#",
    metadata: { Hotel: "Aman Tokyo", Nights: "3", Room: "Imperial Suite" },
  },
  {
    id: "doc-3",
    title: "Japan Electronic Tourist Visa (eVisa)",
    type: "visa",
    holderName: "Alex Rivera",
    issueDate: "2026-07-10",
    expiryDate: "2026-10-10",
    status: "valid",
    fileSize: "2.1 MB",
    downloadUrl: "#",
    metadata: { VisaNumber: "JP-EV-9921448", Entries: "Multiple", StayLimit: "90 Days" },
  },
  {
    id: "doc-4",
    title: "Allianz Global Travel Platinum Medical Insurance",
    type: "insurance",
    holderName: "Alex Rivera",
    issueDate: "2026-08-15",
    expiryDate: "2026-09-25",
    status: "valid",
    fileSize: "1.8 MB",
    downloadUrl: "#",
    metadata: { PolicyNo: "ALZ-MED-449102", MedicalCoverage: "$1,000,000 USD", Evacuation: "Included" },
  },
];

export const SEED_CUSTOMERS: CustomerLead[] = [
  {
    id: "cust-1",
    name: "Sophia Chen",
    email: "sophia.chen@techcorp.io",
    phone: "+1 (415) 890-2199",
    status: "vip",
    budget: 15000,
    preferredDestination: "Maldives & Singapore",
    assignedAgent: "TravelVerse VIP Desk",
    totalBookingsValue: 28400,
    notes: "Requires private seaplane transfers, gluten-free dining, prefers sunrise villas.",
    createdAt: "2026-07-20",
  },
  {
    id: "cust-2",
    name: "Marcus Sterling",
    email: "m.sterling@capitaladvisors.co.uk",
    phone: "+44 20 7946 0912",
    status: "quoted",
    budget: 8500,
    preferredDestination: "Swiss Alps & Zermatt",
    assignedAgent: "Sarah Jenkins",
    totalBookingsValue: 12000,
    notes: "Wants Excellence Class Glacier Express and 5-star ski chalet with indoor pool.",
    createdAt: "2026-08-10",
  },
  {
    id: "cust-3",
    name: "Dr. Aisha Al-Maktoum",
    email: "aisha.m@medicare.ae",
    phone: "+971 50 123 4567",
    status: "booked",
    budget: 32000,
    preferredDestination: "Amalfi Coast & Como Yacht Tour",
    assignedAgent: "Marco Rossi",
    totalBookingsValue: 64500,
    notes: "Family of 5, private helicopter transfers requested from Rome to Capri.",
    createdAt: "2026-08-01",
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    title: "Flight Gate Assigned",
    message: "Flight QA 782 to Tokyo has been assigned Gate 58B at SFO Terminal I. On-time departure.",
    type: "gate_change",
    time: "10 mins ago",
    read: false,
    linkModule: "flights",
  },
  {
    id: "notif-2",
    title: "AI Smart Price Drop Alert",
    message: "First-Class upgrade on your LAX-SYD route dropped by $340. Instant 1-click lock available.",
    type: "price_drop",
    time: "2 hours ago",
    read: false,
    linkModule: "flights",
  },
  {
    id: "notif-3",
    title: "AI Concierge Itinerary Suggestion",
    message: "Rain is forecasted in Tokyo on Day 2 afternoon. We have rearranged your indoor teamLab visit to keep your day dry.",
    type: "ai_recommendation",
    time: "5 hours ago",
    read: true,
    linkModule: "itinerary",
  },
  {
    id: "notif-4",
    title: "Travel Visa Reminder",
    message: "Your Japan Tourist eVisa is confirmed active and attached to your digital wallet pass.",
    type: "document_expiry",
    time: "1 day ago",
    read: true,
    linkModule: "documents",
  },
];
