from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ComparisonCandidate(BaseModel):
    id: str
    name: str
    price: float
    currency: str = "USD"
    rating: Optional[float] = None
    features: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Domain specific data (e.g. flight times)")

class ComparisonRequest(BaseModel):
    candidates: List[ComparisonCandidate]
    preferences: List[str] = Field(default_factory=list, description="User specific needs to determine Best Match")
    # Optional weighting for the Best Value formula. 1.0 means balance price and rating equally.
    quality_weight: float = 1.0 

class ItemAnalysis(BaseModel):
    candidate_id: str
    advantages: List[str]
    disadvantages: List[str]
    tradeoffs: str = Field(..., description="Qualitative summary of the tradeoffs for this option.")

class ComparisonResult(BaseModel):
    cheapest_id: Optional[str] = Field(None, description="Calculated by Python")
    premium_id: Optional[str] = Field(None, description="Calculated by Python")
    best_value_id: Optional[str] = Field(None, description="Calculated by Python formula")
    best_match_id: Optional[str] = Field(None, description="Calculated by Python based on preferences")
    analysis: List[ItemAnalysis] = Field(..., description="Generated by AI")
