from pydantic import BaseModel, Field
from typing import List, Optional, Dict
from datetime import datetime

class PriceDetail(BaseModel):
    amount: float
    currency: str = "USD"
    source: str = Field(..., description="e.g., 'TBO', 'Google', 'Mock', 'User'")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    is_mock: bool = False

class BudgetItem(BaseModel):
    item_id: str
    name: str
    category: str
    price: PriceDetail
    tax: Optional[PriceDetail] = None
    fees: Optional[PriceDetail] = None
    is_essential: bool = False

class BudgetOptimizationRequest(BaseModel):
    flight_prices: List[BudgetItem] = Field(default_factory=list)
    hotel_prices: List[BudgetItem] = Field(default_factory=list)
    transfer_prices: List[BudgetItem] = Field(default_factory=list)
    experience_prices: List[BudgetItem] = Field(default_factory=list)
    budget: float
    currency: str = "USD"
    optimization_goals: List[str] = Field(default_factory=list, description="e.g., 'save on food', 'maximize experiences'")

class AISuggestedCut(BaseModel):
    item_id: str
    reason: str
    suggested_alternative: Optional[str] = None
    estimated_savings: float = 0.0

class BudgetOptimizationResult(BaseModel):
    subtotal: float = Field(..., description="Deterministically calculated sum of base prices")
    total_tax: float = Field(..., description="Deterministically calculated sum of taxes")
    total_fees: float = Field(..., description="Deterministically calculated sum of fees")
    total: float = Field(..., description="subtotal + total_tax + total_fees")
    remaining_budget: float = Field(..., description="budget - total")
    over_budget: bool = Field(..., description="True if remaining_budget < 0")
    
    status: str = Field(..., description="UNDER_BUDGET, OVER_BUDGET, or ON_BUDGET")
    category_percentages: Dict[str, float] = Field(..., description="Deterministic percentage breakdown")
    ai_suggestions: List[str] = Field(default_factory=list, description="Qualitative advice generated by AI")
    suggested_cuts: List[AISuggestedCut] = Field(default_factory=list, description="Items the AI suggests modifying/removing")
