from pydantic import BaseModel, Field
from typing import List, Optional

class BudgetItem(BaseModel):
    item_id: str
    name: str
    category: str
    cost: float
    currency: str = "USD"
    is_essential: bool = False

class BudgetOptimizationRequest(BaseModel):
    items: List[BudgetItem]
    total_budget: float
    currency: str = "USD"
    optimization_goals: List[str] = Field(default_factory=list, description="e.g., 'save on food', 'maximize experiences'")

class AISuggestedCut(BaseModel):
    item_id: str
    reason: str
    suggested_alternative: Optional[str] = None
    estimated_savings: float = 0.0 # Just an estimate from AI

class BudgetOptimizationResult(BaseModel):
    calculated_total: float = Field(..., description="Deterministically calculated sum of items")
    variance: float = Field(..., description="total_budget - calculated_total")
    status: str = Field(..., description="UNDER_BUDGET, OVER_BUDGET, or ON_BUDGET")
    category_percentages: dict[str, float] = Field(..., description="Deterministic percentage breakdown")
    ai_suggestions: List[str] = Field(default_factory=list, description="Qualitative advice generated by AI")
    suggested_cuts: List[AISuggestedCut] = Field(default_factory=list, description="Items the AI suggests modifying/removing")
