from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class PulseAlert(BaseModel):
    severity: str = Field(..., description="high, medium, or low")
    event: str = Field(..., description="The factual event that occurred (e.g., 'Flight AA123 is delayed by 2 hours')")
    impact: str = Field(..., description="The downstream consequence generated by AI (e.g., 'You will likely miss your connection')")
    recommended_action: str = Field(..., description="Actionable advice generated by AI")
    source: str = Field(..., description="System that reported the event (e.g., 'tbo_flight_status', 'weather_provider')")

class TravelPulseRequest(BaseModel):
    trip_id: str
    trip: Dict[str, Any] = Field(default_factory=dict, description="The overall trip document")
    bookings: List[Dict[str, Any]] = Field(default_factory=list, description="All bookings (flights, hotels, activities, transfers) associated with the trip")
    flight_status_payload: List[Dict[str, Any]] = Field(default_factory=list, description="Mocked live flight status data")
    weather_payload: List[Dict[str, Any]] = Field(default_factory=list, description="Mocked live weather warnings")
    system_alerts: List[Dict[str, Any]] = Field(default_factory=list, description="Other system generated alerts")

class TravelPulseResult(BaseModel):
    alerts: List[PulseAlert]
