import { TravelExperience, ExperienceCategory } from "../../types";

export const EXPERIENCE_CATEGORIES: {
  id: ExperienceCategory;
  label: string;
  icon: string;
  description: string;
}[] = [
  {
    id: "Adventure",
    label: "Adventure",
    icon: "🧭",
    description: "Glacier safaris, alpine paragliding, volcano treks & wilderness trails",
  },
  {
    id: "Culture",
    label: "Culture",
    icon: "🏛️",
    description: "Ancient heritage, tea ceremonies, temple rites & museum masterclasses",
  },
  {
    id: "Food",
    label: "Food",
    icon: "🍜",
    description: "Michelin tastings, secret izakayas, market crawls & chef workshops",
  },
  {
    id: "Family",
    label: "Family",
    icon: "👨‍👩‍👧‍👦",
    description: "Interactive studios, wildlife parks, immersive exhibits & theme adventures",
  },
  {
    id: "Nightlife",
    label: "Nightlife",
    icon: "🍸",
    description: "Rooftop lounges, secret speakeasies, jazz clubs & VIP yacht parties",
  },
  {
    id: "Shopping",
    label: "Shopping",
    icon: "🛍️",
    description: "Private styling, haute couture ateliers, artisan souks & vintage luxury",
  },
  {
    id: "Wellness",
    label: "Wellness",
    icon: "🧘",
    description: "Thermal springs, sound baths, holistic retreats & jungle onsens",
  },
  {
    id: "Nature",
    label: "Nature",
    icon: "🌲",
    description: "Alpine lakes, sunset sailing, wildlife encounters & protected reserves",
  },
];

export const SEED_COMPREHENSIVE_EXPERIENCES: TravelExperience[] = [
  // 1. ADVENTURE
  {
    id: "exp-adv-1",
    title: "Reykjavik Aurora Borealis Hunt & Glacier Ice Cave Safari",
    name: "Reykjavik Aurora Borealis Hunt & Glacier Ice Cave Safari",
    category: "Adventure",
    city: "Reykjavik",
    country: "Iceland",
    location: "Vatnajökull & South Coast, Iceland",
    duration: "6 Hours",
    durationHours: 6,
    price: 195,
    originalPrice: 240,
    currency: "USD",
    rating: 4.96,
    reviewsCount: 1420,
    aiMatchScore: 98,
    aiBadge: "98% Match · Arctic Explorer",
    aiMatchReason: "Exceptional match for active travelers seeking celestial Northern Lights and extreme glacial terrain.",
    imageUrl: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPreviewUrl: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=2400&q=80",
    guideLanguage: ["English", "Icelandic"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Board a custom monster 4x4 Superjeep and journey deep into Iceland's volcanic hinterland. Walk inside naturally formed turquoise sapphire ice caves under the Vatnajökull glacier, then track the dancing Northern Lights with a professional astrophotographer while sipping artisanal hot cocoa with Brennivín.",
    meetingPoint: "Reykjavik Terminal / Hotel Pickup included",
    highlights: [
      "Navigate remote volcanic terrain in a modified 44-inch tire 4x4 Superjeep",
      "Spike crampons and explore glowing crystalline sapphire ice caves",
      "Professional astrophotography portrait under the Aurora Borealis included",
      "Warm Icelandic botanical schnapps and warm spiced cocoa around campfire",
    ],
    included: [
      "Superjeep transportation with certified glacier guide",
      "Crampons, helmet, and safety gear",
      "High-resolution digital Aurora photo package",
      "Hot drinks and traditional pastry snacks",
    ],
    notIncluded: ["Thermal winter boot rentals ($15)", "Gratuities"],
    itinerarySchedule: [
      { time: "18:00", activity: "Hotel Pickup & Gear Fitting", description: "Meet your expedition guide and get suited in certified glacier gear." },
      { time: "19:30", activity: "Glacier Sapphire Ice Cave Exploration", description: "Headlamp trek into glowing blue subterranean ice formations." },
      { time: "21:15", activity: "Aurora Chase & Astrophotography", description: "Set up high-sensitivity sensors in pitch-black lava valleys for aurora portraits." },
      { time: "23:45", activity: "Warm Spirits & Return Journey", description: "Hot drinks and return drop-off to your accommodation." },
    ],
    host: {
      name: "Einar Thorvaldsen",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      title: "Glacier Rescue Lead & Astrophotographer",
      badge: "Master Wilderness Guide",
      rating: 4.98,
      verified: true,
    },
    groupSize: "Small Group (Max 8)",
    difficulty: "Moderate",
    minimumAge: 10,
    tags: ["Northern Lights", "Ice Cave", "Superjeep", "Photography", "Winter"],
    reviews: [
      {
        id: "rev-adv-1",
        author: "Marcus Vance",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80",
        rating: 5,
        date: "October 2025",
        comment: "Unbelievable experience! Einar knew the exact weather clearing. Seeing the aurora dance above the glacier ice was pure magic.",
        country: "Canada",
        travelerType: "Solo Traveler",
      },
      {
        id: "rev-adv-2",
        author: "Claire & Daniel",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80",
        rating: 5,
        date: "December 2025",
        comment: "The Superjeep ride felt like driving on Mars. The high-res photos we received the next morning were breathtaking.",
        country: "United Kingdom",
        travelerType: "Couple",
      },
    ],
  },
  {
    id: "exp-adv-2",
    title: "Interlaken Tandem Paragliding over Swiss Alps & Lake Thun",
    name: "Interlaken Tandem Paragliding over Swiss Alps & Lake Thun",
    category: "Adventure",
    city: "Interlaken",
    country: "Switzerland",
    location: "Beatenberg & Höhematte, Interlaken, Switzerland",
    duration: "2 Hours",
    durationHours: 2,
    price: 210,
    originalPrice: 250,
    currency: "USD",
    rating: 4.99,
    reviewsCount: 2180,
    aiMatchScore: 96,
    aiBadge: "96% Match · Alpine Thrillseeker",
    aiMatchReason: "Ideal for travelers craving soaring bird's-eye vistas of the Eiger, Mönch, and Jungfrau peaks.",
    imageUrl: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPreviewUrl: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=2400&q=80",
    guideLanguage: ["English", "German", "French"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Soar effortlessly 1,350 meters above sea level. After a gentle takeoff run from Beatenberg, glide on thermal currents high over turquoise Lake Brienz and Lake Thun with 360-degree panoramas of the snow-capped Bernese Oberland peaks before touching down smoothly in central Interlaken.",
    meetingPoint: "Höhematte Park Landing Base, Höheweg 95, 3800 Interlaken",
    highlights: [
      "Launch from high alpine pastures at Beatenberg with a licensed Swiss tandem pilot",
      "Panoramic glide over both Lake Thun and Lake Brienz simultaneously",
      "Optional G-force spirals and wing-overs for adrenaline enthusiasts",
      "Touchdown smoothly on the manicured grass of Höhematte park",
    ],
    included: ["Licensed tandem pilot", "All safety equipment and wind jacket", "Free shuttle bus to mountain launch"],
    notIncluded: ["GoPro 4K video & photo package on SD card ($40)"],
    itinerarySchedule: [
      { time: "09:00", activity: "Meeting & Safety Briefing", description: "Meet pilot and load onto scenic mountain van to Beatenberg." },
      { time: "09:30", activity: "Pre-Flight Preparation", description: "Harness check and takeoff instructions on the grassy slope." },
      { time: "09:45", activity: "Soaring Flight (15-20 min air time)", description: "Thermal flight catching mountain drafts and alpine panoramas." },
      { time: "10:15", activity: "Touchdown & Media Review", description: "Smooth landing at Höhematte and instant phone photo transfer." },
    ],
    host: {
      name: "Stefan Baumann",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      title: "Swiss Paragliding Federation Pilot (14,000+ flights)",
      badge: "Swiss Alpine Master",
      rating: 5.0,
      verified: true,
    },
    groupSize: "Individual / Tandem pairs",
    difficulty: "Easy",
    minimumAge: 6,
    tags: ["Paragliding", "Alps", "Extreme", "Views", "Summer/Winter"],
  },

  // 2. CULTURE
  {
    id: "exp-cul-1",
    title: "Kyoto Private Tea Ceremony & Gion Geisha District Twilight Walk",
    name: "Kyoto Private Tea Ceremony & Gion Geisha District Twilight Walk",
    category: "Culture",
    city: "Kyoto",
    country: "Japan",
    location: "Gion & Higashiyama, Kyoto, Japan",
    duration: "3.5 Hours",
    durationHours: 3.5,
    price: 145,
    originalPrice: 180,
    currency: "USD",
    rating: 4.98,
    reviewsCount: 1890,
    aiMatchScore: 99,
    aiBadge: "99% Match · Cultural Heritage",
    aiMatchReason: "Perfect match with your appreciation for authentic Japanese zen aesthetics and centuries-old rituals.",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPreviewUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=2400&q=80",
    guideLanguage: ["English", "Japanese"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 48 hours before start",
    cancellationType: "free",
    description:
      "Step inside a 300-year-old preserved Machiya tea sanctuary in Gion. Learn the philosophy of 'Ichigo Ichie' (one time, one meeting) under a certified Urasenke Tea Master. Whisk your own ceremonial Uji matcha paired with seasonal wagashi sweets, followed by an intimate lantern-lit walk through hidden cobblestone alleys of Hanami-koji.",
    meetingPoint: "Yasaka Shrine West Gate (Nishi-romon), Gion, Kyoto",
    highlights: [
      "Exclusive private access to a registered heritage tea pavilion overlooking a moss garden",
      "Hand-whisk single-origin ceremonial grade matcha from historic Uji plantations",
      "Learn the intricate etiquette and philosophy of traditional Japanese Chado",
      "Guided twilight photography walk through Gion's preserved wooden teahouse quarters",
    ],
    included: [
      "Certified Urasenke Master tea ceremony",
      "Ceremonial matcha and handmade artisan seasonal wagashi",
      "Silk kimono dressing experience (optional complimentary upgrade)",
      "Local cultural historian guide",
    ],
    notIncluded: ["Personal souvenir purchases"],
    itinerarySchedule: [
      { time: "16:00", activity: "Meeting at Yasaka Shrine Gate", description: "Introduction to historic Gion and walk to the hidden tea machiya." },
      { time: "16:30", activity: "Traditional Chado Ceremony & Tasting", description: "Purification, meditation, tea preparation, and philosophy talk." },
      { time: "18:00", activity: "Twilight Geisha District Lantern Stroll", description: "Secret stone paths of Shirakawa canal and wooden ochaya." },
      { time: "19:30", activity: "Conclusion & Izakaya Recommendations", description: "Personalized curated map of authentic local dining spots." },
    ],
    host: {
      name: "Sohaku Mori",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      title: "14th Generation Tea Master & Kyoto Historian",
      badge: "Kyoto Heritage Master",
      rating: 4.99,
      verified: true,
    },
    groupSize: "Intimate (Max 6 guests)",
    difficulty: "Easy",
    minimumAge: 8,
    tags: ["Tea Ceremony", "Matcha", "Geisha", "Historic", "Zen"],
  },
  {
    id: "exp-cul-2",
    title: "Rome Colosseum Underground, Arena Floor & Roman Forum VIP Access",
    name: "Rome Colosseum Underground, Arena Floor & Roman Forum VIP Access",
    category: "Culture",
    city: "Rome",
    country: "Italy",
    location: "Piazza del Colosseo, Rome, Italy",
    duration: "3.5 Hours",
    durationHours: 3.5,
    price: 130,
    originalPrice: 165,
    currency: "USD",
    rating: 4.95,
    reviewsCount: 3100,
    aiMatchScore: 97,
    aiBadge: "97% Match · Ancient Wonder",
    aiMatchReason: "Offers rare, skip-the-line underground access away from tourist crowds with a classical archaeologist.",
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=1200&q=80",
    ],
    guideLanguage: ["English", "Italian", "Spanish"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Descend into the restricted subterranean hypogeum of the Flavian Amphitheatre where gladiators and exotic beasts were held before combat. Step out onto the reconstructed wooden Arena stage floor, followed by an archaeologist-led exploration of the Roman Forum and Palatine Hill.",
    meetingPoint: "Arch of Constantine, Piazza del Colosseo, 00184 Roma RM",
    highlights: [
      "Restricted VIP access to the underground hypogeum chambers and trapdoor lift systems",
      "Stand directly on the gladiator arena stage floor with panoramic 360° seating views",
      "Walk the sacred Via Sacra and Julius Caesar's temple in the Roman Forum",
      "Small group led by a PhD classical archaeologist",
    ],
    included: ["VIP Underground & Arena Entry Ticket", "Whisper headsets", "Licensed archaeologist guide"],
    notIncluded: ["Gratuities"],
    host: {
      name: "Dr. Alessia Rossi",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      title: "Roman Archaeologist & Author",
      badge: "Vatican & Colosseum Official",
      rating: 4.97,
      verified: true,
    },
    groupSize: "Small Group (Max 12)",
    difficulty: "Easy",
    minimumAge: 5,
    tags: ["Colosseum", "Archaeology", "History", "VIP Access", "Rome"],
  },

  // 3. FOOD
  {
    id: "exp-food-1",
    title: "Tokyo Cyber-Night Foodie Odyssey: 7 Hidden Izakayas & Alley Bars",
    name: "Tokyo Cyber-Night Foodie Odyssey: 7 Hidden Izakayas & Alley Bars",
    category: "Food",
    city: "Tokyo",
    country: "Japan",
    location: "Shinjuku & Shibuya, Tokyo, Japan",
    duration: "4.5 Hours",
    durationHours: 4.5,
    price: 135,
    originalPrice: 170,
    currency: "USD",
    rating: 4.98,
    reviewsCount: 2450,
    aiMatchScore: 99,
    aiBadge: "99% Match · Culinary Masterpiece",
    aiMatchReason: "Matches your curated taste for authentic street food, artisanal sake pairings, and local neighborhood haunts.",
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPreviewUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=2400&q=80",
    guideLanguage: ["English", "Japanese"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Venture deep into Shinjuku's smokey Omoide Yokocho (Memory Lane) and the neon labyrinth of Golden Gai with a Tokyo-born culinary insider. Savor binchotan charcoal-grilled A5 Wagyu skewers, handmade gyoza, fresh sashimi, seasonal craft sakes, and artisan Japanese whisky in tiny 6-seat subterranean watering holes.",
    meetingPoint: "East Exit of Shinjuku JR Station (Under Studio Alta Large Screen)",
    highlights: [
      "Eat and drink across 7 distinct local izakayas, yakitori stands, and secret speakeasies",
      "Taste melt-in-mouth A5 Miyazaki Wagyu beef skewers and seasonal tsukune",
      "Sommelier-curated tasting of 4 rare regional junmai daiginjo sakes",
      "VIP guaranteed seating in iconic Golden Gai bars where foreigners cannot usually enter alone",
    ],
    included: [
      "All food tastings (equivalent to a generous 8-course dinner)",
      "4 alcoholic beverages (craft sake, highball, draft beer, or soft drinks)",
      "Local insider food guide",
      "Take-home Tokyo Culinary Map & Phrasebook",
    ],
    notIncluded: ["Additional personal cocktail orders"],
    itinerarySchedule: [
      { time: "17:30", activity: "Meeting & Omoide Yokocho Kickoff", description: "Binchotan charcoal yakitori & ice-cold draft beer in narrow retro alley." },
      { time: "18:30", activity: "Subterranean Gyoza & Craft Sake Bar", description: "Crisp handmade dumplings paired with chilled Niigata sake." },
      { time: "19:45", activity: "Kabukicho Secret Ramen & Wagyu Tasting", description: "Rich tonkotsu broth with seared chashu and wagyu slices." },
      { time: "21:00", activity: "Golden Gai Speakeasy Nightcap", description: "Artisanal Japanese whisky tasting in a preserved 1950s miniature bar." },
    ],
    host: {
      name: "Kenji Takahashi",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      title: "Tokyo Food Critic & Certified Sake Sommelier",
      badge: "Michelin Foodie Certified",
      rating: 4.99,
      verified: true,
    },
    groupSize: "Small Group (Max 7)",
    difficulty: "Easy",
    minimumAge: 20,
    tags: ["Izakaya", "Street Food", "Sake", "Wagyu", "Nightlife"],
  },
  {
    id: "exp-food-2",
    title: "Paris Le Marais Gourmet Pastry, Artisan Cheese & Sommelier Wine Tasting",
    name: "Paris Le Marais Gourmet Pastry, Artisan Cheese & Sommelier Wine Tasting",
    category: "Food",
    city: "Paris",
    country: "France",
    location: "Le Marais & Place des Vosges, Paris, France",
    duration: "3.5 Hours",
    durationHours: 3.5,
    price: 155,
    originalPrice: 190,
    currency: "USD",
    rating: 4.97,
    reviewsCount: 1780,
    aiMatchScore: 97,
    aiBadge: "97% Match · Parisian Epicurean",
    aiMatchReason: "Curated for connoisseurs seeking artisan aged cheeses, freshly baked baguettes, and Grand Cru pairings.",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
    ],
    guideLanguage: ["English", "French"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Stroll through the historic cobblestone lanes of Le Marais with a French chef. Stop at century-old fromageries to taste Comté and Roquefort, award-winning boulangeries for flaky croissants, gourmet chocolatiers, and conclude in a private 17th-century cellar for a guided sommelier tasting of Bordeaux and Burgundy wines.",
    meetingPoint: "Metro Saint-Paul (Line 1), Exit 1, Place Saint-Paul, 75004 Paris",
    highlights: [
      "Taste freshly baked award-winning croissants and pistachio éclairs",
      "Visit an affineur master cheese maker for 5 AOC aged French cheeses",
      "Private wine tasting cellar with 4 sommelier-selected French wines",
      "Explore hidden courtyards of Place des Vosges and Hotel de Sully",
    ],
    included: ["All food and pastry tastings", "4 wine pairings", "Chef guide", "Custom gourmet guide to Paris"],
    notIncluded: ["Gratuities"],
    host: {
      name: "Chef Chloé Dubois",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
      title: "Pastry Chef & Le Cordon Bleu Alum",
      badge: "Paris Culinary Specialist",
      rating: 4.98,
      verified: true,
    },
    groupSize: "Intimate (Max 8)",
    difficulty: "Easy",
    minimumAge: 6,
    tags: ["Pastry", "Cheese", "Wine Tasting", "Le Marais", "French Cuisine"],
  },

  // 4. FAMILY
  {
    id: "exp-fam-1",
    title: "Tokyo teamLab Planets & Ghibli Magic Interactive Family Day",
    name: "Tokyo teamLab Planets & Ghibli Magic Interactive Family Day",
    category: "Family",
    city: "Tokyo",
    country: "Japan",
    location: "Toyosu & Mitaka, Tokyo, Japan",
    duration: "5 Hours",
    durationHours: 5,
    price: 110,
    originalPrice: 140,
    currency: "USD",
    rating: 4.96,
    reviewsCount: 3200,
    aiMatchScore: 98,
    aiBadge: "98% Match · Family Wonder",
    aiMatchReason: "Guaranteed ticket entry to Tokyo's top interactive exhibits with private transportation tailored for kids and parents.",
    imageUrl: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    ],
    guideLanguage: ["English", "Japanese"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 48 hours before start",
    cancellationType: "free",
    description:
      "The ultimate stress-free family day in Tokyo. Wade barefoot through waters of floating digital koi fish, immerse inside infinite crystal light universes at teamLab Planets, and discover the whimsical animation magic of Hayao Miyazaki with guaranteed VIP entry.",
    meetingPoint: "Shin-Toyosu Station Exit North or Hotel Pick-up",
    highlights: [
      "Guaranteed priority skip-the-line entry to teamLab Planets immersion",
      "Engaging hands-on scavenger hunt activity pack for kids with collectible stickers",
      "Private family-sized vehicle transfer between sights",
      "Family bento lunch at a themed character garden cafe",
    ],
    included: ["Priority admission tickets", "Private family vehicle transfer", "Character bento lunch", "Kid activity gift pack"],
    notIncluded: ["Museum merchandise store purchases"],
    host: {
      name: "Maya & Kenji",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      title: "Family Travel Specialists & Educators",
      badge: "Kids & Family Expert",
      rating: 4.98,
      verified: true,
    },
    groupSize: "Private Family Groups",
    difficulty: "Easy",
    minimumAge: 2,
    tags: ["teamLab", "Interactive", "Kids Friendly", "Family Fun", "Digital Art"],
  },
  {
    id: "exp-fam-2",
    title: "London Warner Bros. Harry Potter Studios VIP Behind-the-Scenes & Butterbeer",
    name: "London Warner Bros. Harry Potter Studios VIP Behind-the-Scenes & Butterbeer",
    category: "Family",
    city: "London",
    country: "United Kingdom",
    location: "Leavesden Studios & Central London, UK",
    duration: "7 Hours",
    durationHours: 7,
    price: 165,
    originalPrice: 200,
    currency: "USD",
    rating: 4.97,
    reviewsCount: 4100,
    aiMatchScore: 96,
    aiBadge: "96% Match · Wizarding Adventure",
    aiMatchReason: "All-inclusive round-trip luxury electric coach and guaranteed Great Hall access for the whole family.",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1486299267070-83823f5448dd?auto=format&fit=crop&w=1200&q=80",
    ],
    guideLanguage: ["English"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 72 hours before start",
    cancellationType: "flexible",
    description:
      "Step onto the authentic film sets of the Great Hall, stroll down cobblestone Diagon Alley, board the Hogwarts Express on Platform 9 ¾, and explore the secrets of animatronics and magical creature special effects.",
    meetingPoint: "Victoria Coach Station / St Pancras International Pick-up",
    highlights: [
      "Round-trip luxury coach featuring onboard wizarding trivia and films",
      "Walk the authentic stone floor of the Great Hall and Dumbledore's Office",
      "Ride a broomstick over London against a green screen with photo keepsake",
      "Frothy cold Butterbeer and commemorative tankard included",
    ],
    included: ["Studio Tour admission ticket", "Round-trip coach transfer", "Complimentary Butterbeer", "Kids souvenir activity passport"],
    notIncluded: ["Wand shop purchases"],
    host: {
      name: "Arthur Davies",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      title: "Film Historian & Former Warner Bros. Set Guide",
      badge: "Warner Studios Certified",
      rating: 4.96,
      verified: true,
    },
    groupSize: "Small Group / Family",
    difficulty: "Easy",
    minimumAge: 4,
    tags: ["Harry Potter", "Film Sets", "Family Day", "London", "Magic"],
  },

  // 5. NIGHTLIFE
  {
    id: "exp-nit-1",
    title: "Barcelona Gothic Quarter Rooftop Cocktail Hop & Live Flamenco Passion",
    name: "Barcelona Gothic Quarter Rooftop Cocktail Hop & Live Flamenco Passion",
    category: "Nightlife",
    city: "Barcelona",
    country: "Spain",
    location: "Barri Gòtic & El Born, Barcelona, Spain",
    duration: "4 Hours",
    durationHours: 4,
    price: 125,
    originalPrice: 155,
    currency: "USD",
    rating: 4.96,
    reviewsCount: 1650,
    aiMatchScore: 97,
    aiBadge: "97% Match · Vibrant Nightlife",
    aiMatchReason: "Combines VIP rooftop terrace views of the Barcelona Cathedral with passionate, intimate tablao flamenco.",
    imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511527661048-7fe73d85e9a4?auto=format&fit=crop&w=1200&q=80",
    ],
    guideLanguage: ["English", "Spanish"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Experience Barcelona after dark like a true insider. Kick off at a private rooftop overlooking the Gothic Cathedral with sparkling cava, wander through illuminated medieval squares to a secret 17th-century vaulted cellar for raw live flamenco, and finish with craft gin & tonics at an award-winning Born cocktail lounge.",
    meetingPoint: "Plaça de Catalunya by the twin fountains, Barcelona",
    highlights: [
      "Exclusive access to 2 high-end private rooftop cocktail terraces with sunset views",
      "Front-row VIP table at an authentic intimate Gothic tablao flamenco performance",
      "Tasting of traditional Iberian ham tapas, artisanal cheeses, and Spanish vermouth",
      "Skip-the-line entry into the top El Born craft cocktail speakeasy",
    ],
    included: ["3 signature cocktails / premium wine drinks", "Tapas pairing selection", "VIP Flamenco show ticket", "Local nightlife concierge"],
    notIncluded: ["Extra beverages past the 3 included drinks"],
    host: {
      name: "Mateo Ortiz",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      title: "Barcelona Nightlife Host & Sommelier",
      badge: "Catalonia Nightlife Leader",
      rating: 4.96,
      verified: true,
    },
    groupSize: "Small Group (Max 10)",
    difficulty: "Easy",
    minimumAge: 18,
    tags: ["Rooftop Bar", "Flamenco", "Cocktails", "Gothic Quarter", "Tapas"],
  },
  {
    id: "exp-nit-2",
    title: "New York Secret Speakeasies & Greenwich Village Jazz Club VIP",
    name: "New York Secret Speakeasies & Greenwich Village Jazz Club VIP",
    category: "Nightlife",
    city: "New York",
    country: "USA",
    location: "Greenwich Village & East Village, New York, USA",
    duration: "3.5 Hours",
    durationHours: 3.5,
    price: 140,
    originalPrice: 175,
    currency: "USD",
    rating: 4.95,
    reviewsCount: 1980,
    aiMatchScore: 95,
    aiBadge: "95% Match · Jazz & Speakeasy",
    aiMatchReason: "Direct access through hidden phone booths and bookstore doors to legendary underground jazz sessions.",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1200&q=80",
    ],
    guideLanguage: ["English"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Step back into Prohibition-era Manhattan. Enter concealed doorways hidden behind hot dog stands, telephone booths, and vintage tailors. Sip bespoke Prohibition cocktails and conclude with reserved front-row seating at a legendary underground Greenwich Village jazz venue.",
    meetingPoint: "Washington Square Park Arch, New York, NY 10012",
    highlights: [
      "Unlock 3 clandestine NYC speakeasies with secret passwords and hidden entrances",
      "Bespoke mixologist cocktail tailored to your favorite flavor profile",
      "Reserved VIP seating and cover charge included at a famous Village jazz club",
      "Fascinating stories of 1920s bootleggers, mafia history, and jazz icons",
    ],
    included: ["2 craft cocktails", "Jazz club cover charge & reserved table", "Expert local nightlife guide"],
    notIncluded: ["Additional drinks"],
    host: {
      name: "Miles Harrison",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      title: "Jazz Musician & NYC Cocktail Historian",
      badge: "Manhattan Insider",
      rating: 4.97,
      verified: true,
    },
    groupSize: "Small Group (Max 8)",
    difficulty: "Easy",
    minimumAge: 21,
    tags: ["Speakeasy", "Jazz", "Prohibition", "Greenwich Village", "Cocktails"],
  },

  // 6. SHOPPING
  {
    id: "exp-shp-1",
    title: "Milan Quadrilatero della Moda Private Fashion Stylist & Atelier Tour",
    name: "Milan Quadrilatero della Moda Private Fashion Stylist & Atelier Tour",
    category: "Shopping",
    city: "Milan",
    country: "Italy",
    location: "Via Montenapoleone & Via della Spiga, Milan, Italy",
    duration: "4 Hours",
    durationHours: 4,
    price: 260,
    originalPrice: 320,
    currency: "USD",
    rating: 4.97,
    reviewsCount: 890,
    aiMatchScore: 98,
    aiBadge: "98% Match · Haute Couture",
    aiMatchReason: "Bespoke access to private VIP shopping lounges and custom leather workshops in the world's fashion capital.",
    imageUrl: "https://images.unsplash.com/photo-1537832816519-689ad163238b?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1537832816519-689ad163238b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
    ],
    guideLanguage: ["English", "Italian", "French"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 48 hours before start",
    cancellationType: "free",
    description:
      "Walk the iconic Via Montenapoleone with a seasoned Milan Fashion Week personal stylist. Enjoy private salon appointments at heritage Italian fashion houses, explore discreet bespoke shoe and leather ateliers, and receive personalized wardrobe color analysis over Franciacorta sparkling wine.",
    meetingPoint: "Grand Hotel et de Milan, Via Alessandro Manzoni 29, Milan",
    highlights: [
      "1-on-1 personal styling consultation and body silhouette / color palette mapping",
      "Private VIP salon appointments with champagne service at leading designer ateliers",
      "Visit a 4th-generation bespoke leather artisan workshop off the tourist track",
      "Tax-free VAT refund VIP fast-track guidance",
    ],
    included: ["Professional Fashion Stylist", "Private salon access", "Welcome glass of Franciacorta & Italian pastries", "Digital Style Portfolio"],
    notIncluded: ["Clothing / fashion purchases"],
    host: {
      name: "Ginevra Moretti",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      title: "Vogue Italia Stylist & Luxury Brand Consultant",
      badge: "Milan Fashion Chamber Member",
      rating: 4.99,
      verified: true,
    },
    groupSize: "Private (1-3 guests)",
    difficulty: "Easy",
    minimumAge: 16,
    tags: ["Fashion", "Stylist", "Haute Couture", "Milan", "Luxury Shopping"],
  },
  {
    id: "exp-shp-2",
    title: "Tokyo Ginza & Harajuku Vintage Luxury & Streetwear Styling Session",
    name: "Tokyo Ginza & Harajuku Vintage Luxury & Streetwear Styling Session",
    category: "Shopping",
    city: "Tokyo",
    country: "Japan",
    location: "Ginza, Omotesando & Harajuku, Tokyo, Japan",
    duration: "4.5 Hours",
    durationHours: 4.5,
    price: 180,
    originalPrice: 220,
    currency: "USD",
    rating: 4.98,
    reviewsCount: 1120,
    aiMatchScore: 96,
    aiBadge: "96% Match · Streetwear & Vintage",
    aiMatchReason: "Curated treasure hunt through Tokyo's world-renowned mint-condition vintage luxury and Japanese denim boutiques.",
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
    ],
    guideLanguage: ["English", "Japanese"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Uncover Tokyo's most coveted vintage boutiques where Hermès, Chanel, Rolex, and rare Japanese denim (Okayama selvedge) are authenticated and sold at unbeatable prices. Navigate secret second-floor stores in Harajuku and upscale Ginza vaults with a local streetwear designer.",
    meetingPoint: "Ginza Six Central Atrium, Ginza, Tokyo",
    highlights: [
      "Access discreet, invitation-only vintage luxury vaults in Ginza and Daikanyama",
      "Discover rare limited-edition Japanese streetwear, BAPE archives, and selvedge denim",
      "100% authenticity inspection guidance with Japanese certification standards",
      "Tax-free 10% tourist discount assistance on all purchases",
    ],
    included: ["Personal Tokyo Streetwear Stylist", "Curated vintage shopping guide", "Matcha latte break at trendy Omotesando cafe"],
    notIncluded: ["Merchandise purchases"],
    host: {
      name: "Tatsuya Sato",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      title: "Tokyo Fashion Designer & Vintage Curator",
      badge: "Tokyo Streetwear Lead",
      rating: 4.98,
      verified: true,
    },
    groupSize: "Private / Small Group (Max 4)",
    difficulty: "Easy",
    minimumAge: 14,
    tags: ["Vintage", "Luxury", "Streetwear", "Ginza", "Harajuku"],
  },

  // 7. WELLNESS
  {
    id: "exp-wel-1",
    title: "Bali Ubud Sacred Sound Healing & Jungle Waterfall Purification Ritual",
    name: "Bali Ubud Sacred Sound Healing & Jungle Waterfall Purification Ritual",
    category: "Wellness",
    city: "Bali",
    country: "Indonesia",
    location: "Ubud & Sebatu, Bali, Indonesia",
    duration: "5 Hours",
    durationHours: 5,
    price: 115,
    originalPrice: 145,
    currency: "USD",
    rating: 4.99,
    reviewsCount: 2890,
    aiMatchScore: 99,
    aiBadge: "99% Match · Holistic Sanctuary",
    aiMatchReason: "Deeply restorative journey combining traditional Balinese Melukat water cleansing and acoustic Pyramids of Chi sound therapy.",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPreviewUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=2400&q=80",
    guideLanguage: ["English", "Indonesian"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Rebalance your mind, body, and spirit in the lush jungle of Ubud. Experience an ancient Balinese Melukat water blessing ceremony at a sacred jungle waterfall led by a local priest, followed by a deeply immersive 90-minute acoustic sound healing bath in an acoustic pyramid using Tibetan gongs, crystal singing bowls, and didgeridoos.",
    meetingPoint: "Ubud Palace Main Entrance / Hotel Pickup across Ubud",
    highlights: [
      "Sacred Balinese Melukat water cleansing at a secluded sacred holy spring waterfall",
      "Traditional Sarong dressing and blessing ceremony with a local Pemangku priest",
      "90-minute full-body vibration sound bath with antique gongs and quartz crystal singing bowls",
      "Organic plant-based 3-course lunch in a bamboo jungle pavilion overlooking rice terraces",
    ],
    included: [
      "Traditional temple sarong and sash to keep",
      "Priest offering and temple blessing fees",
      "90-minute sound healing session",
      "Organic 3-course farm-to-table lunch & fresh young coconut",
      "Private AC transport",
    ],
    notIncluded: ["Spa treatments beyond sound bath"],
    itinerarySchedule: [
      { time: "08:30", activity: "Hotel Pickup & Scenic Jungle Drive", description: "Journey into the lush Sebatu valley north of Ubud." },
      { time: "09:15", activity: "Sacred Waterfall Melukat Blessing", description: "Purification beneath cascading holy mountain spring waters." },
      { time: "11:00", activity: "Organic Farm-to-Table Bamboo Lunch", description: "Nourishing Balinese botanical cuisine and fresh coconuts." },
      { time: "12:30", activity: "Pyramids of Chi Sacred Sound Bath", description: "Deep meditative acoustic journey using 38-inch bronze gongs." },
    ],
    host: {
      name: "Wayan Sudarta & Ni Made",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
      title: "Balinese Spiritual Healer & Master Sound Practitioner",
      badge: "Holistic Wellness Lead",
      rating: 5.0,
      verified: true,
    },
    groupSize: "Small Group (Max 8)",
    difficulty: "Easy",
    minimumAge: 12,
    tags: ["Sound Healing", "Spiritual", "Waterfall", "Bali", "Meditation"],
  },
  {
    id: "exp-wel-2",
    title: "Iceland Blue Lagoon Premium Geothermal Spa & Silica Mud Sanctuary",
    name: "Iceland Blue Lagoon Premium Geothermal Spa & Silica Mud Sanctuary",
    category: "Wellness",
    city: "Grindavik",
    country: "Iceland",
    location: "Reykjanes Peninsula, Iceland",
    duration: "4.5 Hours",
    durationHours: 4.5,
    price: 160,
    originalPrice: 195,
    currency: "USD",
    rating: 4.96,
    reviewsCount: 5200,
    aiMatchScore: 97,
    aiBadge: "97% Match · Geothermal Oasis",
    aiMatchReason: "World-famous milky blue thermal mineral waters with silica, algae, and mineral scrub masks.",
    imageUrl: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80",
    ],
    guideLanguage: ["English", "Icelandic"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Immerse in the soothing, mineral-rich 39°C geothermal waters of Iceland's world-famous Blue Lagoon. Rejuvenate your skin with pure white silica and nourishing algae masks at the swim-up mask bar, steam in subterranean lava caves, and sip chilled sparkling wine without leaving the lagoon.",
    meetingPoint: "Blue Lagoon Main Entrance (Keflavik / Reykjavik shuttle included)",
    highlights: [
      "Premium all-inclusive entry with towel, bathrobe, and slippers provided",
      "3 therapeutic facial masks at the in-water Mask Bar (Silica, Algae, Mineral Scrub)",
      "Complimentary beverage of choice at the swim-up lagoon bar",
      "Access to geothermal steam caves, saunas, and relaxation lounges",
    ],
    included: ["Premium Entry Ticket", "Use of bathrobe & towel", "3 facial masks", "1 drink of choice", "Roundtrip shuttle"],
    notIncluded: ["In-water floating massage (available on request)"],
    host: {
      name: "Blue Lagoon Wellness Team",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      title: "Geothermal Hydrotherapy Specialists",
      badge: "Iceland Tourism Gold Award",
      rating: 4.96,
      verified: true,
    },
    groupSize: "Flexible",
    difficulty: "Easy",
    minimumAge: 2,
    tags: ["Hot Springs", "Spa", "Geothermal", "Relaxation", "Iceland"],
  },

  // 8. NATURE
  {
    id: "exp-nat-1",
    title: "Santorini Sunset Catamaran Sailing with Caldera Volcanic Springs & BBQ",
    name: "Santorini Sunset Catamaran Sailing with Caldera Volcanic Springs & BBQ",
    category: "Nature",
    city: "Santorini",
    country: "Greece",
    location: "Ammoudi Bay & Caldera, Santorini, Greece",
    duration: "5 Hours",
    durationHours: 5,
    price: 175,
    originalPrice: 220,
    currency: "USD",
    rating: 4.97,
    reviewsCount: 3400,
    aiMatchScore: 99,
    aiBadge: "99% Match · Sunset Perfection",
    aiMatchReason: "World-class sunset cruise sailing past dramatic volcanic cliffs, red beaches, and Aegean hot springs.",
    imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPreviewUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=2400&q=80",
    guideLanguage: ["English", "Greek", "French"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Sail the azure waters of the Aegean on a luxury French catamaran. Anchor at the Red and White beaches for snorkeling, soak in the warm sulfuric geothermal mud springs inside the volcanic caldera, and enjoy a freshly prepared open-air Greek BBQ feast with unlimited Santorini Assyrtiko wine as the sun dips into the sea below Oia.",
    meetingPoint: "Vlychada Marina Pier 4 (Complimentary island-wide hotel transfer)",
    highlights: [
      "Cruise past the dramatic volcanic cliffs, Indian Rock, and the Venetian Lighthouse",
      "Swim and snorkel in crystalline turquoise bays with complimentary gear provided",
      "Soak in the natural sulfuric thermal hot springs of Palea Kameni volcano",
      "Freshly grilled seafood and chicken souvlaki BBQ with Greek salad and local wine",
    ],
    included: [
      "Hotel pickup and drop-off anywhere in Santorini",
      "Freshly prepared Greek BBQ dinner & unlimited local wine, beer, and soft drinks",
      "Snorkeling mask, snorkel, and safety flotation jacket",
      "Towels and onboard Wi-Fi",
    ],
    notIncluded: ["Gratuities for skipper and crew"],
    itinerarySchedule: [
      { time: "14:30", activity: "Hotel Pickup & Marina Boarding", description: "Welcome glass of chilled Greek wine and safety orientation." },
      { time: "15:15", activity: "Red Beach & White Beach Snorkeling", description: "Swim in protected volcanic cove with sea turtles and reef fish." },
      { time: "17:00", activity: "Volcanic Hot Springs Thermal Bath", description: "Anchor inside the caldera for therapeutic mineral dip." },
      { time: "18:45", activity: "Greek BBQ Feast & Sunset under Oia Cliffs", description: "Front-row panoramic sunset toast as the sky turns gold and violet." },
    ],
    host: {
      name: "Captain Nikos & Crew",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      title: "Master Yacht Skipper (22 years Aegean experience)",
      badge: "Aegean Sailing Master",
      rating: 4.98,
      verified: true,
    },
    groupSize: "Semi-Private (Max 14)",
    difficulty: "Easy",
    minimumAge: 0,
    tags: ["Catamaran", "Sunset", "Santorini", "Snorkeling", "BBQ"],
  },
  {
    id: "exp-nat-2",
    title: "Swiss Alps Zermatt Matterhorn Glacier Paradise & Alpine Lakes Trek",
    name: "Swiss Alps Zermatt Matterhorn Glacier Paradise & Alpine Lakes Trek",
    category: "Nature",
    city: "Zermatt",
    country: "Switzerland",
    location: "Gornergrat & Riffelsee, Zermatt, Switzerland",
    duration: "6 Hours",
    durationHours: 6,
    price: 185,
    originalPrice: 230,
    currency: "USD",
    rating: 4.98,
    reviewsCount: 1950,
    aiMatchScore: 98,
    aiBadge: "98% Match · Alpine Majesty",
    aiMatchReason: "Unrivaled views of the iconic Matterhorn reflecting in crystal clear alpine tarns with a Swiss mountain guide.",
    imageUrl: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPreviewUrl: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=2400&q=80",
    guideLanguage: ["English", "German", "French"],
    instantConfirmation: true,
    cancellationPolicy: "Free cancellation up to 24 hours before start",
    cancellationType: "free",
    description:
      "Ride Europe's highest open-air cogwheel railway up to the 3,089-meter Gornergrat observatory. Hike along panoramic alpine paths to Lake Riffelsee where the iconic peak of the Matterhorn is mirrored in the stillness of the water, followed by a traditional Swiss fondue lunch at a historic mountain hut.",
    meetingPoint: "Gornergrat Cogwheel Train Station, Bahnhofplatz, 3920 Zermatt",
    highlights: [
      "Ride the historic Gornergrat Bahn cogwheel train with panoramic window seats",
      "Photograph the postcard-perfect Matterhorn reflection on Lake Riffelsee",
      "Observe 29 four-thousand-meter peaks and the Gorner Glacier from the observatory",
      "Authentic Swiss Alpine cheese fondue and Valais white wine tasting",
    ],
    included: ["Gornergrat return train ticket", "Certified Swiss Mountain Guide", "Swiss fondue lunch and Valais wine", "Trekking poles provided"],
    notIncluded: ["Personal mountaineering boots"],
    host: {
      name: "Hansueli Biner",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      title: "UIAGM Certified Mountain Guide & Zermatt Native",
      badge: "Matterhorn Guide Association",
      rating: 4.99,
      verified: true,
    },
    groupSize: "Small Group (Max 10)",
    difficulty: "Moderate",
    minimumAge: 8,
    tags: ["Matterhorn", "Alps", "Gornergrat", "Trek", "Switzerland"],
  },
];
