import { HotelOffer, HotelSearchParams } from "../../types";

export const SEED_COMPREHENSIVE_HOTELS: HotelOffer[] = [
  {
    id: "ht-201",
    name: "Aman Tokyo Sky Sanctuary",
    city: "Tokyo",
    country: "Japan",
    address: "The Otemachi Tower, 1-5-6 Otemachi, Chiyoda-ku",
    neighborhood: "Otemachi / Marunouchi Financial & Imperial Palace",
    rating: 4.95,
    ratingLabel: "Exceptional",
    starRating: 5,
    reviewsCount: 1420,
    pricePerNight: 890,
    originalPricePerNight: 1050,
    currency: "USD",
    featured: true,
    propertyType: "Skyline Penthouse",
    taxRate: 0.12,
    resortFeePerNight: 35,
    cleanlinessScore: 9.9,
    locationScore: 9.8,
    serviceScore: 9.9,
    valueScore: 9.4,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation until 48 hours before check-in. 100% refund guaranteed.",
    cancellationType: "free",
    aiMatchScore: 99,
    aiBadge: "AI Top Pick",
    aiMatchReason: "99% match for travelers seeking calm minimalist aesthetics, traditional Hinoki wood onsens, and unmatched skyline vistas overlooking Mount Fuji and the Imperial Palace.",
    images: [
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "360° Skyline View",
      "Traditional Onsen Spa",
      "Michelin Omakase",
      "High-speed Starlink",
      "Infinity Lap Pool",
      "Butler Service",
      "Complimentary Breakfast",
      "Fitness Center & Yoga Pavilion",
      "Airport Chauffeur",
      "Valet Parking",
    ],
    neighborhoodHighlights: [
      "Direct indoor access to Otemachi Metro Station (5 lines)",
      "3-minute walk to the East Gardens of the Imperial Palace",
      "10-minute stroll to Tokyo Central Station & Marunouchi Brick Square",
      "Surrounded by world-class omakase counters and luxury boutiques",
    ],
    tags: ["Luxury", "Skyline", "Spa", "Top Rated", "Michelin Dining", "Wellness"],
    description: "Suspended high above the Imperial Palace gardens on floors 33 through 38 of the Otemachi Tower, Aman Tokyo harmonizes monumental Japanese washi architecture with serene granite stone, basalt onsens, and breathtaking metropolis panoramas.",
    coordinates: { lat: 35.6882, lng: 139.7635 },
    rooms: [
      {
        id: "rm-tokyo-1",
        name: "Deluxe Imperial Suite",
        bedType: "1 King Bed + Tatami Lounge",
        capacity: 3,
        pricePerNight: 890,
        sqm: 98,
        sqft: 1054,
        viewType: "Imperial Palace & Mount Fuji View",
        cancellationPolicy: "Free cancellation up to 48h prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 4,
        amenities: [
          "Hinoki Wood Soaking Tub",
          "Complimentary Minibar & Sake",
          "Nespresso Atelier & Japanese Tea Set",
          "Automated Washi Screen Blinds",
          "Dyson Supersonic Hair Care",
          "Bose 700 Surround Sound",
        ],
        specialPerks: ["Complimentary VIP Airport Meet & Greet", "Welcome Matcha Ceremony", "Daily Japanese Breakfast"],
        imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
        gallery: [
          "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80",
        ],
        vrTourAvailable: true,
      },
      {
        id: "rm-tokyo-2",
        name: "Panorama Sky Sanctuary Pavilion",
        bedType: "2 Queen Beds + Living Salon",
        capacity: 4,
        pricePerNight: 1250,
        sqm: 140,
        sqft: 1506,
        viewType: "Panoramic 270° Tokyo Skyline & Tokyo Tower",
        cancellationPolicy: "Free cancellation up to 72h prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 2,
        amenities: [
          "Private In-Suite Onsen Bath",
          "Personal Sommelier Service",
          "Private Dining Terrace",
          "Walk-in Cedar Dressing Room",
          "65-inch OLED Cinema Screen",
          "Sub-Zero Wine Cooler",
        ],
        specialPerks: ["$150 Spa & Dining Credit", "Unlimited Laundry Service", "Late 4:00 PM Check-out"],
        imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80",
        gallery: [
          "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80",
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=80",
        ],
        vrTourAvailable: true,
      },
      {
        id: "rm-tokyo-3",
        name: "Grand Aman Tokyo Penthouse",
        bedType: "1 Master King + 1 Guest Suite",
        capacity: 4,
        pricePerNight: 2400,
        sqm: 210,
        sqft: 2260,
        viewType: "360-Degree Tokyo Horizon",
        cancellationPolicy: "Flexible cancellation up to 7 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 1,
        amenities: [
          "Private Chef Kitchen",
          "Dedicated 24/7 Butler",
          "Custom Steinway Grand Piano",
          "Private Dry Sauna & Cold Plunge",
          "Chauffeured Maybach Fleet",
        ],
        specialPerks: ["Complimentary Roundtrip Helicopter Transfer", "Custom 8-Course Omakase Dinner", "VIP Fast Track"],
        imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-201-1",
        author: "Eleanor Vance",
        country: "United States",
        rating: 5.0,
        date: "July 2026",
        tripType: "Couple",
        title: "Perfection in the clouds above Tokyo",
        comment: "The 30-meter high basalt lobby and the onsen overlooking Mount Fuji are beyond anything we have experienced. The staff knew our names immediately and arranged private after-hours museum entries.",
        pros: "Hinoki bathtub, unmatched peace in the middle of Tokyo, sublime breakfast.",
        cons: "Hard to leave the hotel to explore the city!",
        roomType: "Deluxe Imperial Suite",
        stayDuration: "4 nights",
      },
      {
        id: "rev-201-2",
        author: "Kenji Takahashi",
        country: "Japan",
        rating: 4.9,
        date: "June 2026",
        tripType: "Business",
        title: "The pinnacle of modern Japanese hospitality",
        comment: "Flawless quietude, high-speed Starlink connectivity for global executive calls, and the omakase dinner in the private lounge was unforgettable.",
        pros: "Location in Otemachi, soundproofing, spa wet areas.",
        roomType: "Panorama Sky Sanctuary Pavilion",
        stayDuration: "3 nights",
      },
    ],
  },
  {
    id: "ht-202",
    name: "Soneva Jani Overwater Lagoon",
    city: "Noonu Atoll",
    country: "Maldives",
    address: "Medhufaru Island, Noonu Atoll",
    neighborhood: "Private Lagoon Reserve, 5.6km pristine reef",
    rating: 4.98,
    ratingLabel: "Exceptional",
    starRating: 5,
    reviewsCount: 890,
    pricePerNight: 1480,
    originalPricePerNight: 1750,
    currency: "USD",
    featured: true,
    propertyType: "Luxury Villa",
    taxRate: 0.16,
    resortFeePerNight: 80,
    cleanlinessScore: 10.0,
    locationScore: 9.9,
    serviceScore: 9.9,
    valueScore: 9.3,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation up to 14 days before arrival. Flexible date change.",
    cancellationType: "free",
    aiMatchScore: 98,
    aiBadge: "Best Eco-Luxury",
    aiMatchReason: "98% match for travelers desiring total privacy, overwater slides into bioluminescent waters, and master bedrooms with retractable ceilings for stargazing.",
    images: [
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "Retractable Stargazing Roof",
      "Water Slide into Lagoon",
      "Private Catamaran",
      "Barefoot Butler",
      "Eco-Solar Powered",
      "Overwater Cinema Paradiso",
      "Complimentary Ice Cream & Chocolate Parlour",
      "Private Seaplane Transfers",
      "Coral Reef Diving Center",
    ],
    neighborhoodHighlights: [
      "35-minute scenic seaplane journey from Malé International Airport",
      "Direct house reef access with resident manta rays and sea turtles",
      "100% private secluded island perimeter with no motorized neighbors",
    ],
    tags: ["Ultra-Luxury", "Eco", "Overwater Villa", "Honeymoon", "Private Island"],
    description: "Perched over crystalline turquoise waters, Soneva Jani is the zenith of intelligent luxury. Features private slides straight into the Indian Ocean, zero-waste organic dining, and bedrooms where you press a button to reveal the constellations.",
    coordinates: { lat: 5.8672, lng: 73.3421 },
    rooms: [
      {
        id: "rm-maldives-1",
        name: "1-Bedroom Water Retreat with Curved Slide",
        bedType: "1 Master King Bed + Daybeds",
        capacity: 3,
        pricePerNight: 1480,
        sqm: 411,
        sqft: 4424,
        viewType: "Unobstructed Sunset Turquoise Lagoon",
        cancellationPolicy: "Free cancellation up to 14 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 3,
        amenities: [
          "Private Freshwater Plunge Pool",
          "Curved Water Slide into Lagoon",
          "Retractable Master Bedroom Roof",
          "Catamaran Netting Sunken Lounge",
          "Outdoor Shower & Lagoon Steps",
          "Complimentary Snorkeling Equipment",
        ],
        specialPerks: ["24/7 Dedicated Barefoot Butler", "Free Access to Chocolate & Ice Cream Rooms", "Sunset Dolphin Cruise"],
        imageUrl: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
      {
        id: "rm-maldives-2",
        name: "2-Bedroom Ocean Sanctuary with Private Beach",
        bedType: "2 King Master Suites + Kids Den",
        capacity: 6,
        pricePerNight: 2650,
        sqm: 620,
        sqft: 6673,
        viewType: "Lagoon & Private Sandy Atoll",
        cancellationPolicy: "Free cancellation up to 21 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 1,
        amenities: [
          "Double-Storey Slide & 18m Infinity Pool",
          "Private Gym & Steam Room",
          "Rooftop Dining Sala with Daybeds",
          "Glass Floor Viewing Panels",
        ],
        specialPerks: ["Private Beachside BBQ with Executive Chef", "Unlimited Spa Treatments", "Roundtrip Seaplane"],
        imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-202-1",
        author: "Sophie Laurent",
        country: "France",
        rating: 5.0,
        date: "August 2026",
        tripType: "Couple",
        title: "Heaven on Earth - The slide is unforgettable",
        comment: "Waking up to the roof opening while seeing morning clouds, and sliding directly into warm 28°C turquoise water before breakfast. Our butler 'Friday' made every single wish come true.",
        pros: "Infinite space, food quality, stars at night.",
        roomType: "1-Bedroom Water Retreat with Curved Slide",
        stayDuration: "5 nights",
      },
    ],
  },
  {
    id: "ht-203",
    name: "Canaves Oia Epitome Luxury Suites",
    city: "Santorini",
    country: "Greece",
    address: "Oia Ammoudi Bay, Santorini 847 02",
    neighborhood: "Ammoudi Bay / Oia Cliffs",
    rating: 4.92,
    ratingLabel: "Superb",
    starRating: 5,
    reviewsCount: 1105,
    pricePerNight: 720,
    originalPricePerNight: 850,
    currency: "USD",
    featured: true,
    propertyType: "Resort & Spa",
    taxRate: 0.13,
    resortFeePerNight: 25,
    cleanlinessScore: 9.8,
    locationScore: 9.9,
    serviceScore: 9.7,
    valueScore: 9.2,
    checkInTime: "15:00",
    checkOutTime: "11:00",
    cancellationPolicy: "Free cancellation until 7 days before check-in.",
    cancellationType: "free",
    aiMatchScore: 96,
    aiBadge: "Best Sunset Caldera",
    aiMatchReason: "96% match for romance seekers wanting unobstructed golden hour sunsets away from crowded alleys, with private heated infinity plunge pools and Greek fine dining.",
    images: [
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "Caldera Sunset View",
      "Private Heated Infinity Pool",
      "Private Wine Cellar & Tasting",
      "Helipad Access",
      "Greek Gourmet Bistro",
      "Complimentary Champagne Breakfast",
      "Sunset Yoga Deck",
      "Free Shuttle to Oia Village",
    ],
    neighborhoodHighlights: [
      "5-minute walk down to Ammoudi Bay seafood tavernas and sailing boats",
      "Private tranquil enclave above the village with zero crowd congestion",
      "15-minute scenic path up into Oia's whitewashed churches and galleries",
    ],
    tags: ["Romantic", "Caldera", "Sunset", "Infinity Pool", "Gourmet"],
    description: "Located above the picturesque fishing village of Ammoudi, Canaves Oia Epitome combines earthy volcanic stone with sleek minimalist Cycladic design, offering private heated pools overlooking legendary Aegean sunsets.",
    coordinates: { lat: 36.4618, lng: 25.3753 },
    rooms: [
      {
        id: "rm-santorini-1",
        name: "Epitome Hideaway Villa with Heated Pool",
        bedType: "1 King Bed + Cycladic Daybed",
        capacity: 2,
        pricePerNight: 720,
        sqm: 65,
        sqft: 700,
        viewType: "Unrestricted Aegean Sunset & Sea Horizon",
        cancellationPolicy: "Free cancellation up to 7 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 5,
        amenities: [
          "Private Heated Infinity Pool",
          "Sun Loungers & Shaded Pergola Dining",
          "Open-plan Rainfall Shower",
          "Complimentary Local Assyrtiko Wine & Fruit",
          "Marshall Bluetooth Audio System",
        ],
        specialPerks: ["A la carte Champagne Breakfast served on private terrace", "Port & Airport Shuttle"],
        imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
      {
        id: "rm-santorini-2",
        name: "Grand Sunset Horizon 2-Bedroom Villa",
        bedType: "2 King Bedrooms",
        capacity: 4,
        pricePerNight: 1320,
        sqm: 120,
        sqft: 1290,
        viewType: "Panoramic Caldera & Sea",
        cancellationPolicy: "Free cancellation up to 14 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 2,
        amenities: [
          "Double Heated Pool with In-water Loungers",
          "Outdoor Fire Pit & BBQ Lounge",
          "Jacuzzi Whirlpool",
        ],
        specialPerks: ["Private Sunset Catamaran Cruise Discount", "Dedicated Concierge"],
        imageUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-203-1",
        author: "Marco Rossi",
        country: "Italy",
        rating: 5.0,
        date: "July 2026",
        tripType: "Couple",
        title: "The best sunset view in all of Greece",
        comment: "Being in Ammoudi Bay meant we got the entire sunset directly in front of our pool with no selfie sticks or noisy crowds. The breakfast brought to the room was exceptional.",
        pros: "Privacy, heated pool, phenomenal breakfast.",
        roomType: "Epitome Hideaway Villa with Heated Pool",
        stayDuration: "3 nights",
      },
    ],
  },
  {
    id: "ht-204",
    name: "The Chedi Andermatt Alpine Haven",
    city: "Andermatt",
    country: "Switzerland",
    address: "Gotthardstrasse 4, 6490 Andermatt",
    neighborhood: "Ursern Valley, Swiss Alps",
    rating: 4.90,
    ratingLabel: "Superb",
    starRating: 5,
    reviewsCount: 780,
    pricePerNight: 680,
    originalPricePerNight: 790,
    currency: "USD",
    featured: true,
    propertyType: "Resort & Spa",
    taxRate: 0.10,
    resortFeePerNight: 30,
    cleanlinessScore: 9.9,
    locationScore: 9.6,
    serviceScore: 9.8,
    valueScore: 9.3,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation until 5 days before check-in.",
    cancellationType: "free",
    aiMatchScore: 95,
    aiBadge: "Best Alpine Wellness",
    aiMatchReason: "95% match for mountain enthusiasts wanting a 2,400m² hydrothermal spa, 200 open fireplaces, Michelin Japanese dining, and ski-in butler service.",
    images: [
      "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517840905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "2,400m² Hydrothermal Spa & Baths",
      "Ski Butler & Heated Boot Room",
      "Michelin-Starred Japanese Restaurant",
      "In-Room Open Fireplace",
      "35-meter Indoor Heated Lap Pool",
      "Cheese Tower & Wine Cave",
    ],
    neighborhoodHighlights: [
      "Steps to the Glacier Express historic train station",
      "Direct cable car access to Gemsstock and Sedrun ski domains",
      "Surrounded by pine forests and glacial waterfalls",
    ],
    tags: ["Swiss Alps", "Ski Resort", "Alpine Spa", "Fireplace", "Michelin"],
    description: "Jean-Michel Gathy's Asian-Alpine masterpiece combines Swiss pine and natural stone with Tibetan textiles. Features 200 fireplaces, a 16-meter high glass Cheese Tower, and world-class ski butler services.",
    coordinates: { lat: 46.6341, lng: 8.5947 },
    rooms: [
      {
        id: "rm-swiss-1",
        name: "Deluxe Alpine Room with Fireplace",
        bedType: "1 King Bed (Hästens mattress)",
        capacity: 2,
        pricePerNight: 680,
        sqm: 55,
        sqft: 592,
        viewType: "Ursern Valley & Snow-Capped Peaks",
        cancellationPolicy: "Free cancellation up to 5 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 4,
        amenities: [
          "Glass Fireplace controllable via iPad",
          "Deep Soaking Freestanding Tub & Heated Stone Floors",
          "Complimentary Minibar replenished daily",
          "Acqua di Parma toiletries",
        ],
        specialPerks: ["Free Ski Pass for 2 on 3+ night bookings", "Daily Spa Access & Hydrotherapy"],
        imageUrl: "https://images.unsplash.com/photo-1517840905240-472988babdf9?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-204-1",
        author: "Hannah Schmidt",
        country: "Germany",
        rating: 5.0,
        date: "January 2026",
        tripType: "Couple",
        title: "Cosy luxury at its absolute finest",
        comment: "The ski butlers warming our boots and the indoor pool with mountain views are unbeatable. The cheese sommelier guided us through 40 artisanal Alpine cheeses.",
        pros: "Fireplace, spa pools, ski butler.",
        roomType: "Deluxe Alpine Room with Fireplace",
        stayDuration: "4 nights",
      },
    ],
  },
  {
    id: "ht-205",
    name: "Cheval Blanc Paris Seine Retreat",
    city: "Paris",
    country: "France",
    address: "8 Quai du Louvre, 75001 Paris",
    neighborhood: "1st Arrondissement / Pont Neuf & Seine River",
    rating: 4.94,
    ratingLabel: "Exceptional",
    starRating: 5,
    reviewsCount: 920,
    pricePerNight: 1150,
    originalPricePerNight: 1350,
    currency: "USD",
    featured: true,
    propertyType: "Boutique Hotel",
    taxRate: 0.12,
    resortFeePerNight: 40,
    cleanlinessScore: 9.9,
    locationScore: 10.0,
    serviceScore: 9.9,
    valueScore: 9.1,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation until 48 hours prior to arrival.",
    cancellationType: "free",
    aiMatchScore: 97,
    aiBadge: "Best Art & River View",
    aiMatchReason: "97% match for culture and luxury lovers wanting direct panoramic views of the Pont Neuf, bespoke Dior Spa treatments, and 3-Michelin-star Plénitude dining.",
    images: [
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "Panoramic Seine River Balcony",
      "Dior Spa Paris & Curved Wave Pool",
      "3-Michelin-Star 'Plénitude' Restaurant",
      "Rooftop Garden Bar Le Tout-Paris",
      "24/7 Majordome Service",
      "Art Deco Architecture",
    ],
    neighborhoodHighlights: [
      "Situated directly at Pont Neuf, the oldest bridge in Paris",
      "3-minute walk to the Louvre Museum & Jardin des Tuileries",
      "Direct stroll across the bridge to Saint-Germain-des-Prés cafes",
    ],
    tags: ["Parisian Luxury", "Seine River View", "Dior Spa", "Michelin 3-Star", "Historic"],
    description: "Conceived by Peter Marino inside the legendary Art Deco Samaritaine, Cheval Blanc Paris offers 72 rooms facing the Seine, where French art de vivre meets contemporary Parisian luxury.",
    coordinates: { lat: 48.8584, lng: 2.3429 },
    rooms: [
      {
        id: "rm-paris-1",
        name: "Seine Horizon Junior Suite",
        bedType: "1 King Bed + Velvet Salon",
        capacity: 2,
        pricePerNight: 1150,
        sqm: 65,
        sqft: 700,
        viewType: "Direct Frontal Seine River & Pont Neuf View",
        cancellationPolicy: "Free cancellation up to 48h prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 3,
        amenities: [
          "Winter Garden Balcony with Floor-to-Ceiling Glass",
          "Hammam Steam Shower & Marble Tub",
          "Custom Cheval Blanc Perfumed Amenities",
          "Curated French Contemporary Art Collection",
        ],
        specialPerks: ["VIP Fast-Track Access to Louvre Museum", "Daily Pastries by Chef Maxime Frédéric"],
        imageUrl: "https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-205-1",
        author: "Alexander Wright",
        country: "United Kingdom",
        rating: 5.0,
        date: "May 2026",
        tripType: "Couple",
        title: "An exquisite Parisian masterpiece",
        comment: "Looking down at the boats on the Seine while enjoying fresh croissants from Maxime Frédéric in your winter garden is magical. The Dior Spa pool is stunning.",
        pros: "Location, interior design, culinary brilliance.",
        roomType: "Seine Horizon Junior Suite",
        stayDuration: "3 nights",
      },
    ],
  },
  {
    id: "ht-206",
    name: "The Mark Hotel Upper East Side",
    city: "New York",
    country: "United States",
    address: "25 East 77th Street, New York, NY 10075",
    neighborhood: "Upper East Side / Central Park & Madison Ave",
    rating: 4.88,
    ratingLabel: "Superb",
    starRating: 5,
    reviewsCount: 1240,
    pricePerNight: 695,
    originalPricePerNight: 820,
    currency: "USD",
    featured: false,
    propertyType: "Boutique Hotel",
    taxRate: 0.1475,
    resortFeePerNight: 45,
    cleanlinessScore: 9.8,
    locationScore: 9.9,
    serviceScore: 9.6,
    valueScore: 9.0,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation until 24 hours before check-in.",
    cancellationType: "free",
    aiMatchScore: 94,
    aiBadge: "Best City Classic",
    aiMatchReason: "94% match for travelers seeking chic Jacques Grange design, Jean-Georges culinary delights, and 1 block proximity to Central Park.",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "The Mark Restaurant by Jean-Georges",
      "Custom The Mark Bicycles & Central Park Picnic",
      "Frédéric Fekkai Salon",
      "Chauffeured Bergdorf Goodman Car",
      "Pet Wellness Menu",
      "State-of-the-Art Fitness Center",
    ],
    neighborhoodHighlights: [
      "1 block from Central Park & The Met (Metropolitan Museum of Art)",
      "Surrounded by Madison Avenue designer flagship boutiques",
      "Quiet tree-lined residential brownstone street",
    ],
    tags: ["New York City", "Central Park", "Upper East Side", "Jean-Georges", "Boutique"],
    description: "New York's premier Upper East Side address. Features landmark bold black-and-white striped marble, Jean-Georges Vongerichten dining, and bespoke Central Park picnic butler service.",
    coordinates: { lat: 40.7744, lng: -73.9634 },
    rooms: [
      {
        id: "rm-nyc-1",
        name: "Madison King Premier Room",
        bedType: "1 King Bed with Italian Linens",
        capacity: 2,
        pricePerNight: 695,
        sqm: 45,
        sqft: 485,
        viewType: "77th Street Brownstones View",
        cancellationPolicy: "Free cancellation up to 24h prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 6,
        amenities: [
          "Black and White Marble Bath with Soaking Tub",
          "Bang & Olufsen HD Sound & TV",
          "Custom Sub-Zero Gourmet Pantry Bar",
          "Complimentary Daily New York Times & Shoe Shine",
        ],
        specialPerks: ["Complimentary The Mark Bike Rentals", "Jean-Georges Breakfast Credit"],
        imageUrl: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-206-1",
        author: "David Miller",
        country: "Canada",
        rating: 4.9,
        date: "July 2026",
        tripType: "Family",
        title: "Classic Upper East Side elegance",
        comment: "Walking out into Central Park every morning and coming home to Jean-Georges truffle pizza is unmatched. The pedicab ride arranged by the concierge was delightful.",
        pros: "Location, service, restaurant.",
        roomType: "Madison King Premier Room",
        stayDuration: "4 nights",
      },
    ],
  },
  {
    id: "ht-207",
    name: "Bulgari Resort Bali Cliffside",
    city: "Uluwatu",
    country: "Indonesia",
    address: "Jalan Goa Lempeh, Banjar Dinas Kangin, Uluwatu, Bali 80364",
    neighborhood: "Uluwatu Clifftop / Indian Ocean",
    rating: 4.91,
    ratingLabel: "Superb",
    starRating: 5,
    reviewsCount: 640,
    pricePerNight: 850,
    originalPricePerNight: 980,
    currency: "USD",
    featured: true,
    propertyType: "Luxury Villa",
    taxRate: 0.11,
    resortFeePerNight: 35,
    cleanlinessScore: 9.8,
    locationScore: 9.9,
    serviceScore: 9.8,
    valueScore: 9.3,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation until 7 days before check-in.",
    cancellationType: "free",
    aiMatchScore: 96,
    aiBadge: "Best Clifftop Luxury",
    aiMatchReason: "96% match for travelers seeking dramatic 150m cliff ocean views, private funicular beach access, and Balinese-Italian architectural harmony.",
    images: [
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "150m Clifftop Ocean Panorama",
      "Private Incline Funicular to Beach",
      "Il Ristorante - Luca Fantin Michelin Dining",
      "Private Plunge Pool & Sun Deck",
      "Open-Air Oceanfront Spa Pavilion",
      "Bespoke Helicopter Tours",
    ],
    neighborhoodHighlights: [
      "10-minute drive to Uluwatu Temple & Sunset Kecak Dance",
      "Private access to secluded stretch of pristine white sand beach",
      "World-class surf breaks along the southern Bukit peninsula",
    ],
    tags: ["Bali", "Ocean Cliff", "Private Pool", "Spa", "Italian Design"],
    description: "Combining dramatic Balinese natural beauty with exquisite Italian contemporary elegance, Bulgari Resort Bali sits 150 meters above the roaring Indian Ocean with private ocean villas and a private beach funicular.",
    coordinates: { lat: -8.8471, lng: 115.1436 },
    rooms: [
      {
        id: "rm-bali-1",
        name: "Ocean View Cliffside Villa with Pool",
        bedType: "1 Four-Poster King Bed",
        capacity: 2,
        pricePerNight: 850,
        sqm: 300,
        sqft: 3229,
        viewType: "Panoramic 180° Indian Ocean Clifftop",
        cancellationPolicy: "Free cancellation up to 7 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 4,
        amenities: [
          "Private Plunge Pool & Outdoor Living Pavilion",
          "Black Volcanic Stone Sunken Bathtub",
          "Bulgari Luxury Fragrance Amenity Kit",
          "Bang & Olufsen Entertainment System",
        ],
        specialPerks: ["Daily Afternoon High Tea", "Clifftop Sunset Cocktail for 2"],
        imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-207-1",
        author: "Emily Chen",
        country: "Singapore",
        rating: 5.0,
        date: "June 2026",
        tripType: "Couple",
        title: "Breathtaking cliff ocean vistas",
        comment: "Taking the funicular down the cliff face to the private beach club and swimming in our private clifftop pool while watching the waves crash below was utterly magical.",
        pros: "Views, privacy, dining.",
        roomType: "Ocean View Cliffside Villa with Pool",
        stayDuration: "4 nights",
      },
    ],
  },
  {
    id: "ht-208",
    name: "Le Sirenuse Positano Sanctuary",
    city: "Positano",
    country: "Italy",
    address: "Via Cristoforo Colombo 30, 84017 Positano",
    neighborhood: "Amalfi Coast / Positano Bay",
    rating: 4.93,
    ratingLabel: "Exceptional",
    starRating: 5,
    reviewsCount: 810,
    pricePerNight: 950,
    originalPricePerNight: 1100,
    currency: "USD",
    featured: true,
    propertyType: "Boutique Hotel",
    taxRate: 0.10,
    resortFeePerNight: 30,
    cleanlinessScore: 9.8,
    locationScore: 10.0,
    serviceScore: 9.9,
    valueScore: 9.1,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation until 14 days before arrival.",
    cancellationType: "free",
    aiMatchScore: 97,
    aiBadge: "Best Mediterranean Charm",
    aiMatchReason: "97% match for romance and iconic Amalfi scenery, family-run warmth since 1951, candlelit terrace dining, and antique Italian tile craftsmanship.",
    images: [
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "Iconic Positano Cliffside Panorama",
      "La Sponda 400-Candlelit Restaurant",
      "Franco's Bar Sunset Cocktails",
      "Heated Lemon-Tree Pool",
      "Private Riva Wooden Speedboat Excursions",
      "Aveda Aromatherapy Spa",
    ],
    neighborhoodHighlights: [
      "Located in the prime center of Positano cascading down to the beach",
      "5-minute stroll through bougainvillea paths to Spiaggia Grande",
      "Private boat departures directly to Capri and Amalfi",
    ],
    tags: ["Amalfi Coast", "Positano", "Romantic", "Candlelit Dining", "Historic"],
    description: "An 18th-century noble summer residence turned boutique legend. Le Sirenuse overlooks the pastel cliff houses of Positano with 400 candles illuminating La Sponda every evening.",
    coordinates: { lat: 40.6281, lng: 14.485 },
    rooms: [
      {
        id: "rm-positano-1",
        name: "Sea View Junior Suite with Balcony",
        bedType: "1 King Bed + Handmade Vietri Majolica Tiles",
        capacity: 2,
        pricePerNight: 950,
        sqm: 50,
        sqft: 538,
        viewType: "Direct Positano Bay & Pastel Cascading Village",
        cancellationPolicy: "Free cancellation up to 14 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 3,
        amenities: [
          "Furnished Balcony with Positano Panorama",
          "Whirlpool Hydro-Massage Tub",
          "Eau d'Italie Signature Toiletries",
          "Original Antique Art & Furnishings",
        ],
        specialPerks: ["Complimentary Morning Wooden Boat Cruise along Amalfi Cliffs", "Welcome Prosecco"],
        imageUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-208-1",
        author: "Charlotte Dubois",
        country: "Monaco",
        rating: 5.0,
        date: "June 2026",
        tripType: "Couple",
        title: "The spirit of the Amalfi Coast",
        comment: "Dinner at La Sponda with the 400 candles and acoustic mandolin players was the most romantic evening of our lives. The view from our balcony at sunset is unmatched.",
        pros: "Atmosphere, views, food, staff attention.",
        roomType: "Sea View Junior Suite with Balcony",
        stayDuration: "3 nights",
      },
    ],
  },
  {
    id: "ht-209",
    name: "Hoshinoya Kyoto Bamboo Sanctuary",
    city: "Kyoto",
    country: "Japan",
    address: "11-2 Arashiyama Genrokuzan-cho, Nishikyo-ku, Kyoto 616-0007",
    neighborhood: "Arashiyama / Oi River & Bamboo Groves",
    rating: 4.96,
    ratingLabel: "Exceptional",
    starRating: 5,
    reviewsCount: 520,
    pricePerNight: 820,
    originalPricePerNight: 940,
    currency: "USD",
    featured: true,
    propertyType: "Heritage Palace",
    taxRate: 0.10,
    resortFeePerNight: 20,
    cleanlinessScore: 10.0,
    locationScore: 9.8,
    serviceScore: 10.0,
    valueScore: 9.4,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation until 10 days before check-in.",
    cancellationType: "free",
    aiMatchScore: 98,
    aiBadge: "Best Zen Heritage",
    aiMatchReason: "98% match for guests seeking peaceful traditional boat arrivals along the Oi River, kaiseki gastronomy, and serene maple foliage views.",
    images: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "Traditional Wooden Boat Arrival on Oi River",
      "Michelin Kaiseki Haute Cuisine",
      "Morning Buddhist Temple Meditation",
      "Tatami Mattresses with Cypress Aroma",
      "Waterfront Tea Pavilion",
      "Kyo-karakami Handcrafted Woodblock Art",
    ],
    neighborhoodHighlights: [
      "Reached exclusively by a 15-minute scenic wooden boat glide from Togetsukyo Bridge",
      "Nestled inside the protected Arashiyama forested valley",
      "Surrounded by historic UNESCO Zen temples like Tenryu-ji",
    ],
    tags: ["Kyoto", "Ryokan", "Zen", "Kaiseki", "Nature Sanctuary"],
    description: "Accessible only by a gentle 15-minute boat ride up the Oi River, Hoshinoya Kyoto breathes new life into a 17th-century riverside merchant estate, delivering pure silence and timeless Japanese aesthetics.",
    coordinates: { lat: 35.0116, lng: 135.6778 },
    rooms: [
      {
        id: "rm-kyoto-1",
        name: "Tsukihashi Riverside Pavilion",
        bedType: "2 Japanese Low Beds + Tatami Room",
        capacity: 3,
        pricePerNight: 820,
        sqm: 72,
        sqft: 775,
        viewType: "Oi River & Arashiyama Maple Hillsides",
        cancellationPolicy: "Free cancellation up to 10 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 2,
        amenities: [
          "Cedarwood Soaking Tub overlooking River",
          "Kyo-karakami Washi Wallpaper & Intricate Wood Carvings",
          "Traditional Incense Burning Set",
          "Japanese Silk Kimono Yukatas",
        ],
        specialPerks: ["Private Tea Master Ceremony", "Morning Zen Meditation with Monk"],
        imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-209-1",
        author: "Liam O'Connor",
        country: "Ireland",
        rating: 5.0,
        date: "April 2026",
        tripType: "Couple",
        title: "A spiritual step back in time",
        comment: "Taking the wooden boat up the misty river to arrive at the ryokan is unforgettable. The kaiseki meal was a 10-course work of art.",
        pros: "Boat arrival, quiet, kaiseki dinner.",
        roomType: "Tsukihashi Riverside Pavilion",
        stayDuration: "2 nights",
      },
    ],
  },
  {
    id: "ht-210",
    name: "Burj Al Arab Jumeirah Royal Haven",
    city: "Dubai",
    country: "United Arab Emirates",
    address: "Jumeirah Beach Road, Dubai",
    neighborhood: "Jumeirah Beach / Private Island Sanctuary",
    rating: 4.95,
    ratingLabel: "Exceptional",
    starRating: 5,
    reviewsCount: 1680,
    pricePerNight: 1350,
    originalPricePerNight: 1600,
    currency: "USD",
    featured: true,
    propertyType: "Skyline Penthouse",
    taxRate: 0.10,
    resortFeePerNight: 50,
    cleanlinessScore: 9.9,
    locationScore: 9.8,
    serviceScore: 9.9,
    valueScore: 9.2,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation until 48 hours before check-in.",
    cancellationType: "free",
    aiMatchScore: 97,
    aiBadge: "Best 7-Star Grandeur",
    aiMatchReason: "97% match for travelers seeking legendary 24-karat gold leaf luxury, two-story suites, private beach club infinity pool terrace, and personal Rolls Royce transfers.",
    images: [
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "2-Story Duplex All-Suite Layout",
      "Hermès Full-Size Amenities Collection",
      "Private Butler per Floor",
      "Sal Beach Club Luxury Cabanas & Pools",
      "Al Mahara Underwater Michelin Dining",
      "Helipad Transfers & Rolls-Royce Phantom Fleet",
    ],
    neighborhoodHighlights: [
      "Built on its own private reclaimed island 280m offshore",
      "Connected by private bridge to Jumeirah Beach",
      "15 minutes to Dubai Marina and Downtown Burj Khalifa",
    ],
    tags: ["Dubai", "Ultra-Luxury", "Duplex Suite", "Hermes", "Private Island"],
    description: "The world's most recognizable sail-shaped icon. Burj Al Arab offers duplex suites with 24-karat gold leaf, rotating canopy beds, and a terrace with infinity saltwater pools stretching over the Arabian Gulf.",
    coordinates: { lat: 25.1412, lng: 55.1852 },
    rooms: [
      {
        id: "rm-dubai-1",
        name: "Deluxe Duplex 1-Bedroom Suite",
        bedType: "1 Rotating Master King Bed",
        capacity: 2,
        pricePerNight: 1350,
        sqm: 170,
        sqft: 1830,
        viewType: "Panoramic Arabian Gulf Horizon",
        cancellationPolicy: "Free cancellation up to 48h prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 4,
        amenities: [
          "2-Storey Layout with Spiral Marble Staircase",
          "Full-Size Hermès Fragrances & Bath Bar",
          "Private Bar & Dining Salon",
          "Jacuzzi Whirlpool overlooking the Gulf",
        ],
        specialPerks: ["Rolls Royce Phantom Airport Transfer", "Unlimited Access to Wild Wadi & Sal Pool"],
        imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-210-1",
        author: "Fahad Al-Mansoor",
        country: "United Arab Emirates",
        rating: 5.0,
        date: "July 2026",
        tripType: "Business",
        title: "Still the gold standard of world hospitality",
        comment: "The duplex suite gives an immense sense of volume. The butler was anticipating every single need before we even spoke.",
        pros: "Scale, service, Hermès amenities, terrace pool.",
        roomType: "Deluxe Duplex 1-Bedroom Suite",
        stayDuration: "3 nights",
      },
    ],
  },
  {
    id: "ht-211",
    name: "The Berkeley Knightsbridge Luxury",
    city: "London",
    country: "United Kingdom",
    address: "Wilton Place, Knightsbridge, London SW1X 7RL",
    neighborhood: "Knightsbridge / Hyde Park & Belgravia",
    rating: 4.89,
    ratingLabel: "Superb",
    starRating: 5,
    reviewsCount: 940,
    pricePerNight: 640,
    originalPricePerNight: 760,
    currency: "USD",
    featured: false,
    propertyType: "Boutique Hotel",
    taxRate: 0.20,
    resortFeePerNight: 25,
    cleanlinessScore: 9.8,
    locationScore: 9.9,
    serviceScore: 9.7,
    valueScore: 9.1,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    cancellationPolicy: "Free cancellation until 24 hours prior to check-in.",
    cancellationType: "free",
    aiMatchScore: 93,
    aiBadge: "Best Rooftop Pool",
    aiMatchReason: "93% match for visitors wanting Knightsbridge shopping, a secret rooftop pool overlooking Hyde Park, and famous Prêt-à-Portea fashion afternoon tea.",
    images: [
      "https://images.unsplash.com/photo-1517840905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1517840905240-472988babdf9?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "Rooftop Swimming Pool overlooking Hyde Park",
      "Prêt-à-Portea Fashion Afternoon Tea",
      "Bamford Haybarn Wellness Spa",
      "Cedric Grolet Bakery in-house",
      "Private Chauffeur Car",
      "Balcony Suites",
    ],
    neighborhoodHighlights: [
      "2-minute walk to Harrods & Harvey Nichols luxury department stores",
      "Directly opposite Hyde Park & Kensington Gardens",
      "10 minutes to Buckingham Palace and Mayfair galleries",
    ],
    tags: ["London", "Knightsbridge", "Rooftop Pool", "Hyde Park", "Harrods"],
    description: "An invigorating modern luxury staple in Knightsbridge. Features chic interiors by André Fu, the legendary Cedric Grolet pastry boutique, and London's chicest rooftop heated pool.",
    coordinates: { lat: 51.502, lng: -0.1578 },
    rooms: [
      {
        id: "rm-london-1",
        name: "Knightsbridge Pavilion Suite with Park Terrace",
        bedType: "1 King Bed + Dressing Salon",
        capacity: 2,
        pricePerNight: 640,
        sqm: 48,
        sqft: 516,
        viewType: "Hyde Park Tree Canopy & Wilton Place",
        cancellationPolicy: "Free cancellation up to 24h prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 5,
        amenities: [
          "Private Glass Balcony with Hyde Park Views",
          "Italian Marble Bathroom with Underfloor Heating",
          "Bamford Organic Botanicals",
          "Bespoke Cocktail Mixing Trolley",
        ],
        specialPerks: ["Priority Seating for Cedric Grolet Bakery", "Daily Full English Breakfast"],
        imageUrl: "https://images.unsplash.com/photo-1517840905240-472988babdf9?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-211-1",
        author: "James Sterling",
        country: "United Kingdom",
        rating: 4.9,
        date: "July 2026",
        tripType: "Business",
        title: "The best hotel pool in London",
        comment: "Swimming on the roof overlooking the trees of Hyde Park in the morning is the most refreshing experience in London. The Cedric Grolet croissants are divine.",
        pros: "Rooftop pool, pastries, prime Knightsbridge location.",
        roomType: "Knightsbridge Pavilion Suite with Park Terrace",
        stayDuration: "3 nights",
      },
    ],
  },
  {
    id: "ht-212",
    name: "The Retreat at Blue Lagoon Geothermal",
    city: "Grindavík",
    country: "Iceland",
    address: "Nordurljosavegur 11, 240 Grindavík",
    neighborhood: "Reykjanes UNESCO Geopark & Geothermal Lava Field",
    rating: 4.94,
    ratingLabel: "Exceptional",
    starRating: 5,
    reviewsCount: 710,
    pricePerNight: 1200,
    originalPricePerNight: 1390,
    currency: "USD",
    featured: true,
    propertyType: "Eco-Lodge",
    taxRate: 0.11,
    resortFeePerNight: 40,
    cleanlinessScore: 9.9,
    locationScore: 9.8,
    serviceScore: 9.9,
    valueScore: 9.3,
    checkInTime: "15:00",
    checkOutTime: "11:00",
    cancellationPolicy: "Free cancellation until 14 days before arrival.",
    cancellationType: "free",
    aiMatchScore: 96,
    aiBadge: "Best Thermal Sanctuary",
    aiMatchReason: "96% match for travelers seeking private mineral-rich geothermal waters, moss-covered volcanic architecture, and northern lights observatory deck.",
    images: [
      "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517840905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
    ],
    vrPanoramaUrl: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=2400&q=80",
    amenities: [
      "Private Retreat Lagoon (Direct Suite Access)",
      "The Blue Lagoon Ritual Spa (Silica, Algae, Mineral)",
      "Moss Michelin Guide Nordic Restaurant",
      "Northern Lights Wake-up Call Service",
      "Subterranean Lava Steam Caves",
      "Unlimited Geothermal Wine Lounge",
    ],
    neighborhoodHighlights: [
      "Surrounded by an 800-year-old moss-covered lava field",
      "20 minutes from Keflavík International Airport",
      "Located in Reykjanes UNESCO Global Geopark",
    ],
    tags: ["Iceland", "Geothermal", "Blue Lagoon", "Spa", "Northern Lights"],
    description: "Carved directly into an 800-year-old lava field, The Retreat at Blue Lagoon unlocks a subterranean sanctuary with private geothermal waters, minimalist Nordic luxury, and the legendary Blue Lagoon Ritual.",
    coordinates: { lat: 63.8804, lng: -22.4495 },
    rooms: [
      {
        id: "rm-iceland-1",
        name: "Lagoon Suite with Direct Private Geothermal Access",
        bedType: "1 King Bed with Icelandic Down Linens",
        capacity: 2,
        pricePerNight: 1200,
        sqm: 60,
        sqft: 645,
        viewType: "Private Turquoise Geothermal Lagoon & Lava Wall",
        cancellationPolicy: "Free cancellation up to 14 days prior",
        refundable: true,
        breakfastIncluded: true,
        availableRoomsCount: 2,
        amenities: [
          "Private Geothermal Water Entry directly from Suite Terrace",
          "Freestanding Tub overlooking Volcanic Formations",
          "Full Blue Lagoon Skincare Amenity Suite",
          "Fireplace and Icelandic Oak Finishes",
        ],
        specialPerks: ["Exclusive Access to The Retreat Spa & Ritual", "Daily Afternoon Icelandic Tasting"],
        imageUrl: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1000&q=80",
        vrTourAvailable: true,
      },
    ],
    reviews: [
      {
        id: "rev-212-1",
        author: "Astrid Lindgren",
        country: "Sweden",
        rating: 5.0,
        date: "February 2026",
        tripType: "Couple",
        title: "Stepping directly into warm mineral water from bed",
        comment: "Opening your balcony door and sliding into steaming 39°C blue waters surrounded by snow and black volcanic rocks is heaven. The Silica mask treatment makes your skin baby soft.",
        pros: "Private lagoon, ritual spa, silence.",
        roomType: "Lagoon Suite with Direct Private Geothermal Access",
        stayDuration: "2 nights",
      },
    ],
  },
];

// Popular destinations for the hotel discovery landing page
export const POPULAR_HOTEL_DESTINATIONS = [
  {
    city: "Tokyo",
    country: "Japan",
    tagline: "Skyline onsens & Michelin mastery",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
    propertiesCount: 18,
    startPrice: 420,
    badge: "Trending",
  },
  {
    city: "Noonu Atoll",
    country: "Maldives",
    tagline: "Overwater slides & bioluminescent lagoons",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    propertiesCount: 12,
    startPrice: 890,
    badge: "Ultra-Luxury",
  },
  {
    city: "Santorini",
    country: "Greece",
    tagline: "Caldera infinity pools & golden sunsets",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80",
    propertiesCount: 24,
    startPrice: 380,
    badge: "Romance",
  },
  {
    city: "Paris",
    country: "France",
    tagline: "Seine river balconies & haute gastronomy",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    propertiesCount: 31,
    startPrice: 450,
    badge: "Popular",
  },
  {
    city: "Andermatt",
    country: "Switzerland",
    tagline: "Alpine fireside spas & ski-in butlers",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=80",
    propertiesCount: 9,
    startPrice: 520,
    badge: "Winter Bliss",
  },
  {
    city: "Kyoto",
    country: "Japan",
    tagline: "Riverside ryokans & private tea pavilions",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
    propertiesCount: 16,
    startPrice: 490,
    badge: "Zen Escapes",
  },
];

// Curated collections
export const HOTEL_CURATED_COLLECTIONS = [
  {
    id: "col-overwater",
    title: "Overwater Villas & Private Island Sanctuaries",
    description: "Direct ladder drops into crystal lagoons, glass floor panels, and stargazing roofs.",
    count: 14,
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=800&q=80",
    filterTag: "Overwater Villa",
  },
  {
    id: "col-skyline",
    title: "Metropolis Skyline Penthouses & Onsens",
    description: "Floor-to-ceiling glass high above vibrant world capitals with Michelin omakase.",
    count: 22,
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
    filterTag: "Skyline",
  },
  {
    id: "col-alpine",
    title: "Alpine Chalets & Hydrothermal Spas",
    description: "Cosy open fireplaces, heated outdoor snow pools, and glacier view suites.",
    count: 11,
    image: "https://images.unsplash.com/photo-1517840905240-472988babdf9?auto=format&fit=crop&w=800&q=80",
    filterTag: "Alpine Spa",
  },
  {
    id: "col-caldera",
    title: "Cycladic Cliffside Pools & Sunsets",
    description: "Private heated plunge pools overlooking Mediterranean caldera horizons.",
    count: 19,
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80",
    filterTag: "Caldera",
  },
];

// Helper search function that filters and sorts hotels
export function searchHotels(params: HotelSearchParams): HotelOffer[] {
  let results = [...SEED_COMPREHENSIVE_HOTELS];

  // Destination filter
  if (params.destination && params.destination.trim() !== "" && params.destination.toLowerCase() !== "all") {
    const query = params.destination.toLowerCase().trim();
    results = results.filter((h) => {
      return (
        h.city.toLowerCase().includes(query) ||
        h.country.toLowerCase().includes(query) ||
        h.name.toLowerCase().includes(query) ||
        h.neighborhood?.toLowerCase().includes(query) ||
        h.tags.some((t) => t.toLowerCase().includes(query))
      );
    });
  }

  // Guest count filtering (at least one room can fit the guests or total capacity)
  const totalGuests = (params.guests?.adults || 1) + (params.guests?.children || 0);
  if (totalGuests > 1) {
    results = results.filter((h) => {
      return h.rooms.some((r) => r.capacity >= Math.ceil(totalGuests / (params.rooms || 1)));
    });
  }

  // Price range
  if (params.minPrice !== undefined) {
    results = results.filter((h) => h.pricePerNight >= params.minPrice!);
  }
  if (params.maxPrice !== undefined && params.maxPrice > 0) {
    results = results.filter((h) => h.pricePerNight <= params.maxPrice!);
  }

  // Rating
  if (params.minRating !== undefined && params.minRating > 0) {
    results = results.filter((h) => h.rating >= params.minRating!);
  }

  // AI Match score threshold
  if (params.minAiMatchScore !== undefined && params.minAiMatchScore > 0) {
    results = results.filter((h) => (h.aiMatchScore || 90) >= params.minAiMatchScore!);
  }

  // Star ratings
  if (params.starRatings && params.starRatings.length > 0) {
    results = results.filter((h) => params.starRatings!.includes(h.starRating || 5));
  }

  // Amenities
  if (params.amenities && params.amenities.length > 0) {
    results = results.filter((h) => {
      return params.amenities!.every((reqAmenity) =>
        h.amenities.some((a) => a.toLowerCase().includes(reqAmenity.toLowerCase()))
      );
    });
  }

  // Property types
  if (params.propertyTypes && params.propertyTypes.length > 0) {
    results = results.filter((h) => {
      return params.propertyTypes!.includes(h.propertyType || "Resort & Spa");
    });
  }

  // Free cancellation
  if (params.freeCancellationOnly) {
    results = results.filter((h) => h.cancellationType === "free");
  }

  // Breakfast included
  if (params.breakfastIncludedOnly) {
    results = results.filter((h) => h.rooms.some((r) => r.breakfastIncluded));
  }

  // Sort
  if (params.sortBy) {
    switch (params.sortBy) {
      case "ai_match":
        results.sort((a, b) => (b.aiMatchScore || 90) - (a.aiMatchScore || 90));
        break;
      case "price_low":
        results.sort((a, b) => a.pricePerNight - b.pricePerNight);
        break;
      case "price_high":
        results.sort((a, b) => b.pricePerNight - a.pricePerNight);
        break;
      case "rating_high":
        results.sort((a, b) => b.rating - a.rating);
        break;
      case "popularity":
        results.sort((a, b) => b.reviewsCount - a.reviewsCount);
        break;
      default:
        results.sort((a, b) => (b.aiMatchScore || 90) - (a.aiMatchScore || 90));
        break;
    }
  } else {
    // Default sort by AI match
    results.sort((a, b) => (b.aiMatchScore || 90) - (a.aiMatchScore || 90));
  }

  return results;
}

// Calculate stay price breakdown helper
export function calculateStayPrice(hotel: HotelOffer, room: { pricePerNight: number }, nights: number, roomsCount: number = 1) {
  const safeNights = Math.max(1, nights || 1);
  const baseSubtotal = room.pricePerNight * safeNights * roomsCount;
  const taxRate = hotel.taxRate || 0.12;
  const taxes = Math.round(baseSubtotal * taxRate);
  const resortFees = (hotel.resortFeePerNight || 35) * safeNights * roomsCount;
  const totalPrice = baseSubtotal + taxes + resortFees;

  return {
    nights: safeNights,
    roomsCount,
    nightlyRate: room.pricePerNight,
    baseSubtotal,
    taxRate,
    taxes,
    resortFeePerNight: hotel.resortFeePerNight || 35,
    resortFees,
    totalPrice,
  };
}
